// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type AddPartitionsToTxnResponse struct {
	ThrottleTimeMs           int32
	ErrorCode                int16
	ResultsByTransaction     []AddPartitionsToTxnResponseAddPartitionsToTxnResult
	ResultsByTopicV3AndBelow []AddPartitionsToTxnResponseAddPartitionsToTxnTopicResult
}

type AddPartitionsToTxnResponseAddPartitionsToTxnPartitionResult struct {
	PartitionIndex     int32
	PartitionErrorCode int16
}

type AddPartitionsToTxnResponseAddPartitionsToTxnResult struct {
	TransactionalId string
	TopicResults    []AddPartitionsToTxnResponseAddPartitionsToTxnTopicResult
}

type AddPartitionsToTxnResponseAddPartitionsToTxnTopicResult struct {
	Name               string
	ResultsByPartition []AddPartitionsToTxnResponseAddPartitionsToTxnPartitionResult
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *AddPartitionsToTxnResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("AddPartitionsToTxnResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("AddPartitionsToTxnResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *AddPartitionsToTxnResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("AddPartitionsToTxnResponse v%d: %w", version, err)
	}
	return nil
}

func (m *AddPartitionsToTxnResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	if version >= 4 {
		{
			v, err := r.ReadInt16()
			if err != nil {
				return err
			}
			m.ErrorCode = v
		}
	}
	if version >= 4 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.ResultsByTransaction = make([]AddPartitionsToTxnResponseAddPartitionsToTxnResult, n)
				for i := 0; i < n; i++ {
					if err := m.ResultsByTransaction[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if version <= 3 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.ResultsByTopicV3AndBelow = make([]AddPartitionsToTxnResponseAddPartitionsToTxnTopicResult, n)
				for i := 0; i < n; i++ {
					if err := m.ResultsByTopicV3AndBelow[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AddPartitionsToTxnResponseAddPartitionsToTxnPartitionResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.PartitionErrorCode = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AddPartitionsToTxnResponseAddPartitionsToTxnResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 4 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.TransactionalId = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.TransactionalId = v
		}
	}
	if version >= 4 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.TopicResults = make([]AddPartitionsToTxnResponseAddPartitionsToTxnTopicResult, n)
				for i := 0; i < n; i++ {
					if err := m.TopicResults[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AddPartitionsToTxnResponseAddPartitionsToTxnTopicResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.ResultsByPartition = make([]AddPartitionsToTxnResponseAddPartitionsToTxnPartitionResult, n)
			for i := 0; i < n; i++ {
				if err := m.ResultsByPartition[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AddPartitionsToTxnResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	if version >= 4 {
		w.WriteInt16(m.ErrorCode)
	}
	if version >= 4 {
		{
			n := len(m.ResultsByTransaction)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.ResultsByTransaction[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if version <= 3 {
		{
			n := len(m.ResultsByTopicV3AndBelow)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.ResultsByTopicV3AndBelow[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AddPartitionsToTxnResponseAddPartitionsToTxnPartitionResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt16(m.PartitionErrorCode)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AddPartitionsToTxnResponseAddPartitionsToTxnResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 4 {
		if flexible {
			w.WriteCompactString(m.TransactionalId)
		} else {
			w.WriteString(m.TransactionalId)
		}
	}
	if version >= 4 {
		{
			n := len(m.TopicResults)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.TopicResults[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AddPartitionsToTxnResponseAddPartitionsToTxnTopicResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	{
		n := len(m.ResultsByPartition)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.ResultsByPartition[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
