// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type AddOffsetsToTxnRequest struct {
	TransactionalId string
	ProducerId      int64
	ProducerEpoch   int16
	GroupId         string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *AddOffsetsToTxnRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("AddOffsetsToTxnRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("AddOffsetsToTxnRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *AddOffsetsToTxnRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("AddOffsetsToTxnRequest v%d: %w", version, err)
	}
	return nil
}

func (m *AddOffsetsToTxnRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.TransactionalId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.TransactionalId = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.ProducerId = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ProducerEpoch = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupId = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AddOffsetsToTxnRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if flexible {
		w.WriteCompactString(m.TransactionalId)
	} else {
		w.WriteString(m.TransactionalId)
	}
	w.WriteInt64(m.ProducerId)
	w.WriteInt16(m.ProducerEpoch)
	if flexible {
		w.WriteCompactString(m.GroupId)
	} else {
		w.WriteString(m.GroupId)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
