// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type AlterPartitionRequest struct {
	BrokerId    int32
	BrokerEpoch int64
	Topics      []AlterPartitionRequestTopicData
}

type AlterPartitionRequestBrokerState struct {
	BrokerId    int32
	BrokerEpoch int64
}

type AlterPartitionRequestPartitionData struct {
	PartitionIndex      int32
	LeaderEpoch         int32
	NewIsr              []int32
	NewIsrWithEpochs    []AlterPartitionRequestBrokerState
	LeaderRecoveryState int8
	PartitionEpoch      int32
}

type AlterPartitionRequestTopicData struct {
	TopicId    [16]byte
	Partitions []AlterPartitionRequestPartitionData
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *AlterPartitionRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("AlterPartitionRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("AlterPartitionRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *AlterPartitionRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("AlterPartitionRequest v%d: %w", version, err)
	}
	return nil
}

func (m *AlterPartitionRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.BrokerId = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.BrokerEpoch = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]AlterPartitionRequestTopicData, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterPartitionRequestBrokerState) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if version >= 3 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.BrokerId = v
		}
	}
	if version >= 3 {
		{
			v, err := r.ReadInt64()
			if err != nil {
				return err
			}
			m.BrokerEpoch = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterPartitionRequestPartitionData) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderEpoch = v
	}
	if version <= 2 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.NewIsr = make([]int32, n)
				for i := 0; i < n; i++ {
					{
						v, err := r.ReadInt32()
						if err != nil {
							return err
						}
						m.NewIsr[i] = v
					}
				}
			}
		}
	}
	if version >= 3 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.NewIsrWithEpochs = make([]AlterPartitionRequestBrokerState, n)
				for i := 0; i < n; i++ {
					if err := m.NewIsrWithEpochs[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if version >= 1 {
		{
			v, err := r.ReadInt8()
			if err != nil {
				return err
			}
			m.LeaderRecoveryState = v
		}
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionEpoch = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterPartitionRequestTopicData) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if version >= 2 {
		{
			v, err := r.ReadUUID()
			if err != nil {
				return err
			}
			m.TopicId = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]AlterPartitionRequestPartitionData, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterPartitionRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.BrokerId)
	w.WriteInt64(m.BrokerEpoch)
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AlterPartitionRequestBrokerState) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if version >= 3 {
		w.WriteInt32(m.BrokerId)
	}
	if version >= 3 {
		w.WriteInt64(m.BrokerEpoch)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AlterPartitionRequestPartitionData) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt32(m.LeaderEpoch)
	if version <= 2 {
		{
			n := len(m.NewIsr)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				w.WriteInt32(m.NewIsr[i])
			}
		}
	}
	if version >= 3 {
		{
			n := len(m.NewIsrWithEpochs)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.NewIsrWithEpochs[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if version >= 1 {
		w.WriteInt8(m.LeaderRecoveryState)
	}
	w.WriteInt32(m.PartitionEpoch)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AlterPartitionRequestTopicData) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if version >= 2 {
		w.WriteUUID(m.TopicId)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
