// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type AlterPartitionReassignmentsResponse struct {
	ThrottleTimeMs               int32
	AllowReplicationFactorChange bool
	ErrorCode                    int16
	ErrorMessage                 *string
	Responses                    []AlterPartitionReassignmentsResponseReassignableTopicResponse
}

type AlterPartitionReassignmentsResponseReassignablePartitionResponse struct {
	PartitionIndex int32
	ErrorCode      int16
	ErrorMessage   *string
}

type AlterPartitionReassignmentsResponseReassignableTopicResponse struct {
	Name       string
	Partitions []AlterPartitionReassignmentsResponseReassignablePartitionResponse
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *AlterPartitionReassignmentsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("AlterPartitionReassignmentsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("AlterPartitionReassignmentsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *AlterPartitionReassignmentsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("AlterPartitionReassignmentsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *AlterPartitionReassignmentsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	if version >= 1 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.AllowReplicationFactorChange = v
		}
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Responses = make([]AlterPartitionReassignmentsResponseReassignableTopicResponse, n)
			for i := 0; i < n; i++ {
				if err := m.Responses[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterPartitionReassignmentsResponseReassignablePartitionResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterPartitionReassignmentsResponseReassignableTopicResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]AlterPartitionReassignmentsResponseReassignablePartitionResponse, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterPartitionReassignmentsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	if version >= 1 {
		w.WriteBool(m.AllowReplicationFactorChange)
	}
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	{
		n := len(m.Responses)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Responses[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AlterPartitionReassignmentsResponseReassignablePartitionResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AlterPartitionReassignmentsResponseReassignableTopicResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
