// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type AlterUserScramCredentialsRequest struct {
	Deletions  []AlterUserScramCredentialsRequestScramCredentialDeletion
	Upsertions []AlterUserScramCredentialsRequestScramCredentialUpsertion
}

type AlterUserScramCredentialsRequestScramCredentialDeletion struct {
	Name      string
	Mechanism int8
}

type AlterUserScramCredentialsRequestScramCredentialUpsertion struct {
	Name           string
	Mechanism      int8
	Iterations     int32
	Salt           []byte
	SaltedPassword []byte
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *AlterUserScramCredentialsRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("AlterUserScramCredentialsRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("AlterUserScramCredentialsRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *AlterUserScramCredentialsRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("AlterUserScramCredentialsRequest v%d: %w", version, err)
	}
	return nil
}

func (m *AlterUserScramCredentialsRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Deletions = make([]AlterUserScramCredentialsRequestScramCredentialDeletion, n)
			for i := 0; i < n; i++ {
				if err := m.Deletions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Upsertions = make([]AlterUserScramCredentialsRequestScramCredentialUpsertion, n)
			for i := 0; i < n; i++ {
				if err := m.Upsertions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterUserScramCredentialsRequestScramCredentialDeletion) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.Mechanism = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterUserScramCredentialsRequestScramCredentialUpsertion) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.Mechanism = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Iterations = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.Salt = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.Salt = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.SaltedPassword = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.SaltedPassword = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *AlterUserScramCredentialsRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		n := len(m.Deletions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Deletions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.Upsertions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Upsertions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AlterUserScramCredentialsRequestScramCredentialDeletion) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	w.WriteInt8(m.Mechanism)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *AlterUserScramCredentialsRequestScramCredentialUpsertion) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	w.WriteInt8(m.Mechanism)
	w.WriteInt32(m.Iterations)
	if flexible {
		w.WriteCompactBytes(m.Salt)
	} else {
		w.WriteBytes(m.Salt)
	}
	if flexible {
		w.WriteCompactBytes(m.SaltedPassword)
	} else {
		w.WriteBytes(m.SaltedPassword)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
