// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ApiVersionsRequest struct {
	ClientSoftwareName    string
	ClientSoftwareVersion string
	ClusterId             *string
	NodeId                int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ApiVersionsRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ApiVersionsRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ApiVersionsRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ApiVersionsRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ApiVersionsRequest v%d: %w", version, err)
	}
	return nil
}

func (m *ApiVersionsRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 3 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.ClientSoftwareName = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.ClientSoftwareName = v
		}
	}
	if version >= 3 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.ClientSoftwareVersion = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.ClientSoftwareVersion = v
		}
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.ClusterId = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.ClusterId = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.ClusterId = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.ClusterId = &s
			}
		}
	}
	if version >= 5 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.NodeId = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ApiVersionsRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 3 {
		if flexible {
			w.WriteCompactString(m.ClientSoftwareName)
		} else {
			w.WriteString(m.ClientSoftwareName)
		}
	}
	if version >= 3 {
		if flexible {
			w.WriteCompactString(m.ClientSoftwareVersion)
		} else {
			w.WriteString(m.ClientSoftwareVersion)
		}
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				w.WriteCompactNullableString(m.ClusterId)
			} else {
				w.WriteNullableString(m.ClusterId)
			}
		} else {
			if m.ClusterId == nil {
				return fmt.Errorf("ClusterId: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.ClusterId)
			} else {
				w.WriteString(*m.ClusterId)
			}
		}
	}
	if version >= 5 {
		w.WriteInt32(m.NodeId)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
