// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type BeginQuorumEpochRequest struct {
	ClusterId       *string
	VoterId         int32
	Topics          []BeginQuorumEpochRequestTopicData
	LeaderEndpoints []BeginQuorumEpochRequestLeaderEndpoint
}

type BeginQuorumEpochRequestLeaderEndpoint struct {
	Name string
	Host string
	Port uint16
}

type BeginQuorumEpochRequestPartitionData struct {
	PartitionIndex   int32
	VoterDirectoryId [16]byte
	LeaderId         int32
	LeaderEpoch      int32
}

type BeginQuorumEpochRequestTopicData struct {
	TopicName  string
	Partitions []BeginQuorumEpochRequestPartitionData
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *BeginQuorumEpochRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("BeginQuorumEpochRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("BeginQuorumEpochRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *BeginQuorumEpochRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("BeginQuorumEpochRequest v%d: %w", version, err)
	}
	return nil
}

func (m *BeginQuorumEpochRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ClusterId = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ClusterId = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.VoterId = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]BeginQuorumEpochRequestTopicData, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if version >= 1 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.LeaderEndpoints = make([]BeginQuorumEpochRequestLeaderEndpoint, n)
				for i := 0; i < n; i++ {
					if err := m.LeaderEndpoints[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *BeginQuorumEpochRequestLeaderEndpoint) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if version >= 1 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Name = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Name = v
		}
	}
	if version >= 1 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Host = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Host = v
		}
	}
	if version >= 1 {
		{
			v, err := r.ReadUint16()
			if err != nil {
				return err
			}
			m.Port = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *BeginQuorumEpochRequestPartitionData) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	if version >= 1 {
		{
			v, err := r.ReadUUID()
			if err != nil {
				return err
			}
			m.VoterDirectoryId = v
		}
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderEpoch = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *BeginQuorumEpochRequestTopicData) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.TopicName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.TopicName = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]BeginQuorumEpochRequestPartitionData, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *BeginQuorumEpochRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		w.WriteCompactNullableString(m.ClusterId)
	} else {
		w.WriteNullableString(m.ClusterId)
	}
	if version >= 1 {
		w.WriteInt32(m.VoterId)
	}
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if version >= 1 {
		{
			n := len(m.LeaderEndpoints)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.LeaderEndpoints[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *BeginQuorumEpochRequestLeaderEndpoint) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if version >= 1 {
		if flexible {
			w.WriteCompactString(m.Name)
		} else {
			w.WriteString(m.Name)
		}
	}
	if version >= 1 {
		if flexible {
			w.WriteCompactString(m.Host)
		} else {
			w.WriteString(m.Host)
		}
	}
	if version >= 1 {
		w.WriteUint16(m.Port)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *BeginQuorumEpochRequestPartitionData) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	if version >= 1 {
		w.WriteUUID(m.VoterDirectoryId)
	}
	w.WriteInt32(m.LeaderId)
	w.WriteInt32(m.LeaderEpoch)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *BeginQuorumEpochRequestTopicData) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		w.WriteCompactString(m.TopicName)
	} else {
		w.WriteString(m.TopicName)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
