// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type BrokerHeartbeatRequest struct {
	BrokerId              int32
	BrokerEpoch           int64
	CurrentMetadataOffset int64
	WantFence             bool
	WantShutDown          bool
	OfflineLogDirs        [][16]byte
	CordonedLogDirs       [][16]byte
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *BrokerHeartbeatRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("BrokerHeartbeatRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("BrokerHeartbeatRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *BrokerHeartbeatRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("BrokerHeartbeatRequest v%d: %w", version, err)
	}
	return nil
}

func (m *BrokerHeartbeatRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.BrokerId = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.BrokerEpoch = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.CurrentMetadataOffset = v
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.WantFence = v
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.WantShutDown = v
	}
	if flexible {
		if err := r.ReadTaggedFields(func(tag uint64, sub *Reader) error {
			switch tag {
			case 0:
				if !(version >= 1) {
					return nil
				}
				{
					var n int
					var err error
					if true {
						n, err = sub.ReadCompactArrayLen()
					} else {
						n, err = sub.ReadArrayLen()
					}
					if err != nil {
						return err
					}
					if n >= 0 {
						m.OfflineLogDirs = make([][16]byte, n)
						for i := 0; i < n; i++ {
							{
								v, err := sub.ReadUUID()
								if err != nil {
									return err
								}
								m.OfflineLogDirs[i] = v
							}
						}
					}
				}
			case 1:
				if !(version >= 2) {
					return nil
				}
				{
					var n int
					var err error
					if true {
						n, err = sub.ReadCompactArrayLen()
					} else {
						n, err = sub.ReadArrayLen()
					}
					if err != nil {
						return err
					}
					if n >= 0 {
						m.CordonedLogDirs = make([][16]byte, n)
						for i := 0; i < n; i++ {
							{
								v, err := sub.ReadUUID()
								if err != nil {
									return err
								}
								m.CordonedLogDirs[i] = v
							}
						}
					}
				}
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func (m *BrokerHeartbeatRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.BrokerId)
	w.WriteInt64(m.BrokerEpoch)
	w.WriteInt64(m.CurrentMetadataOffset)
	w.WriteBool(m.WantFence)
	w.WriteBool(m.WantShutDown)
	if flexible {
		var tfs []TaggedField
		if version >= 1 {
			sub := NewWriter()
			{
				n := len(m.OfflineLogDirs)
				if true {
					sub.WriteCompactArrayLen(n)
				} else {
					sub.WriteArrayLen(n)
				}
				for i := 0; i < n; i++ {
					sub.WriteUUID(m.OfflineLogDirs[i])
				}
			}
			tfs = append(tfs, TaggedField{Tag: 0, Body: sub.Bytes()})
		}
		if version >= 2 {
			sub := NewWriter()
			{
				if (version >= 2) && m.CordonedLogDirs == nil {
					if true {
						sub.WriteCompactArrayLen(-1)
					} else {
						sub.WriteArrayLen(-1)
					}
				} else {
					n := len(m.CordonedLogDirs)
					if true {
						sub.WriteCompactArrayLen(n)
					} else {
						sub.WriteArrayLen(n)
					}
					for i := 0; i < n; i++ {
						sub.WriteUUID(m.CordonedLogDirs[i])
					}
				}
			}
			tfs = append(tfs, TaggedField{Tag: 1, Body: sub.Bytes()})
		}
		w.WriteTaggedFields(tfs)
	}
	return nil
}
