// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type BrokerRegistrationRequest struct {
	BrokerId            int32
	ClusterId           string
	IncarnationId       [16]byte
	Listeners           []BrokerRegistrationRequestListener
	Features            []BrokerRegistrationRequestFeature
	Rack                *string
	IsMigratingZkBroker bool
	LogDirs             [][16]byte
	PreviousBrokerEpoch int64
}

type BrokerRegistrationRequestFeature struct {
	Name                string
	MinSupportedVersion int16
	MaxSupportedVersion int16
}

type BrokerRegistrationRequestListener struct {
	Name             string
	Host             string
	Port             uint16
	SecurityProtocol int16
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *BrokerRegistrationRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("BrokerRegistrationRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("BrokerRegistrationRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *BrokerRegistrationRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("BrokerRegistrationRequest v%d: %w", version, err)
	}
	return nil
}

func (m *BrokerRegistrationRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.BrokerId = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ClusterId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ClusterId = v
	}
	{
		v, err := r.ReadUUID()
		if err != nil {
			return err
		}
		m.IncarnationId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Listeners = make([]BrokerRegistrationRequestListener, n)
			for i := 0; i < n; i++ {
				if err := m.Listeners[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Features = make([]BrokerRegistrationRequestFeature, n)
			for i := 0; i < n; i++ {
				if err := m.Features[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.Rack = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.Rack = v
	}
	if version >= 1 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.IsMigratingZkBroker = v
		}
	}
	if version >= 2 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.LogDirs = make([][16]byte, n)
				for i := 0; i < n; i++ {
					{
						v, err := r.ReadUUID()
						if err != nil {
							return err
						}
						m.LogDirs[i] = v
					}
				}
			}
		}
	}
	if version >= 3 {
		{
			v, err := r.ReadInt64()
			if err != nil {
				return err
			}
			m.PreviousBrokerEpoch = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *BrokerRegistrationRequestFeature) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.MinSupportedVersion = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.MaxSupportedVersion = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *BrokerRegistrationRequestListener) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Host = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Host = v
	}
	{
		v, err := r.ReadUint16()
		if err != nil {
			return err
		}
		m.Port = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.SecurityProtocol = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *BrokerRegistrationRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.BrokerId)
	if flexible {
		w.WriteCompactString(m.ClusterId)
	} else {
		w.WriteString(m.ClusterId)
	}
	w.WriteUUID(m.IncarnationId)
	{
		n := len(m.Listeners)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Listeners[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.Features)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Features[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteCompactNullableString(m.Rack)
	} else {
		w.WriteNullableString(m.Rack)
	}
	if version >= 1 {
		w.WriteBool(m.IsMigratingZkBroker)
	}
	if version >= 2 {
		{
			n := len(m.LogDirs)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				w.WriteUUID(m.LogDirs[i])
			}
		}
	}
	if version >= 3 {
		w.WriteInt64(m.PreviousBrokerEpoch)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *BrokerRegistrationRequestFeature) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	w.WriteInt16(m.MinSupportedVersion)
	w.WriteInt16(m.MaxSupportedVersion)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *BrokerRegistrationRequestListener) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	if flexible {
		w.WriteCompactString(m.Host)
	} else {
		w.WriteString(m.Host)
	}
	w.WriteUint16(m.Port)
	w.WriteInt16(m.SecurityProtocol)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
