// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ConsumerProtocolAssignment struct {
	AssignedPartitions []ConsumerProtocolAssignmentTopicPartition
	UserData           []byte
}

type ConsumerProtocolAssignmentTopicPartition struct {
	Topic      string
	Partitions []int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ConsumerProtocolAssignment) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ConsumerProtocolAssignment v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ConsumerProtocolAssignment v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ConsumerProtocolAssignment) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ConsumerProtocolAssignment v%d: %w", version, err)
	}
	return nil
}

func (m *ConsumerProtocolAssignment) decode(r *Reader, version int16) error {
	_ = version
	flexible := false
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.AssignedPartitions = make([]ConsumerProtocolAssignmentTopicPartition, n)
			for i := 0; i < n; i++ {
				if err := m.AssignedPartitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.UserData = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.UserData = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ConsumerProtocolAssignmentTopicPartition) decode(r *Reader, version int16) error {
	_ = version
	flexible := false
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Topic = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Topic = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.Partitions[i] = v
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ConsumerProtocolAssignment) encode(w *Writer, version int16) error {
	_ = version
	flexible := false
	_ = flexible
	{
		n := len(m.AssignedPartitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.AssignedPartitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteCompactBytes(m.UserData)
	} else {
		w.WriteBytes(m.UserData)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ConsumerProtocolAssignmentTopicPartition) encode(w *Writer, version int16) error {
	_ = version
	flexible := false
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Topic)
	} else {
		w.WriteString(m.Topic)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt32(m.Partitions[i])
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
