// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type CreateDelegationTokenResponse struct {
	ErrorCode                   int16
	PrincipalType               string
	PrincipalName               string
	TokenRequesterPrincipalType string
	TokenRequesterPrincipalName string
	IssueTimestampMs            int64
	ExpiryTimestampMs           int64
	MaxTimestampMs              int64
	TokenId                     string
	Hmac                        []byte
	ThrottleTimeMs              int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *CreateDelegationTokenResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("CreateDelegationTokenResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("CreateDelegationTokenResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *CreateDelegationTokenResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("CreateDelegationTokenResponse v%d: %w", version, err)
	}
	return nil
}

func (m *CreateDelegationTokenResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.PrincipalType = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.PrincipalType = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.PrincipalName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.PrincipalName = v
	}
	if version >= 3 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.TokenRequesterPrincipalType = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.TokenRequesterPrincipalType = v
		}
	}
	if version >= 3 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.TokenRequesterPrincipalName = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.TokenRequesterPrincipalName = v
		}
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.IssueTimestampMs = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.ExpiryTimestampMs = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.MaxTimestampMs = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.TokenId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.TokenId = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.Hmac = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.Hmac = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *CreateDelegationTokenResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactString(m.PrincipalType)
	} else {
		w.WriteString(m.PrincipalType)
	}
	if flexible {
		w.WriteCompactString(m.PrincipalName)
	} else {
		w.WriteString(m.PrincipalName)
	}
	if version >= 3 {
		if flexible {
			w.WriteCompactString(m.TokenRequesterPrincipalType)
		} else {
			w.WriteString(m.TokenRequesterPrincipalType)
		}
	}
	if version >= 3 {
		if flexible {
			w.WriteCompactString(m.TokenRequesterPrincipalName)
		} else {
			w.WriteString(m.TokenRequesterPrincipalName)
		}
	}
	w.WriteInt64(m.IssueTimestampMs)
	w.WriteInt64(m.ExpiryTimestampMs)
	w.WriteInt64(m.MaxTimestampMs)
	if flexible {
		w.WriteCompactString(m.TokenId)
	} else {
		w.WriteString(m.TokenId)
	}
	if flexible {
		w.WriteCompactBytes(m.Hmac)
	} else {
		w.WriteBytes(m.Hmac)
	}
	w.WriteInt32(m.ThrottleTimeMs)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
