// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type CreatePartitionsResponse struct {
	ThrottleTimeMs int32
	Results        []CreatePartitionsResponseCreatePartitionsTopicResult
}

type CreatePartitionsResponseCreatePartitionsTopicResult struct {
	Name         string
	ErrorCode    int16
	ErrorMessage *string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *CreatePartitionsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("CreatePartitionsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("CreatePartitionsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *CreatePartitionsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("CreatePartitionsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *CreatePartitionsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Results = make([]CreatePartitionsResponseCreatePartitionsTopicResult, n)
			for i := 0; i < n; i++ {
				if err := m.Results[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *CreatePartitionsResponseCreatePartitionsTopicResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *CreatePartitionsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	{
		n := len(m.Results)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Results[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *CreatePartitionsResponseCreatePartitionsTopicResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
