// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type CreateTopicsResponse struct {
	ThrottleTimeMs int32
	Topics         []CreateTopicsResponseCreatableTopicResult
}

type CreateTopicsResponseCreatableTopicConfigs struct {
	Name         string
	Value        *string
	ReadOnly     bool
	ConfigSource int8
	IsSensitive  bool
}

type CreateTopicsResponseCreatableTopicResult struct {
	Name                 string
	TopicId              [16]byte
	ErrorCode            int16
	ErrorMessage         *string
	TopicConfigErrorCode int16
	NumPartitions        int32
	ReplicationFactor    int16
	Configs              []CreateTopicsResponseCreatableTopicConfigs
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *CreateTopicsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("CreateTopicsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("CreateTopicsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *CreateTopicsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("CreateTopicsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *CreateTopicsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if version >= 2 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.ThrottleTimeMs = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]CreateTopicsResponseCreatableTopicResult, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *CreateTopicsResponseCreatableTopicConfigs) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if version >= 5 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Name = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Name = v
		}
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.Value = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.Value = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.Value = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.Value = &s
			}
		}
	}
	if version >= 5 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.ReadOnly = v
		}
	}
	if version >= 5 {
		{
			v, err := r.ReadInt8()
			if err != nil {
				return err
			}
			m.ConfigSource = v
		}
	}
	if version >= 5 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.IsSensitive = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *CreateTopicsResponseCreatableTopicResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	if version >= 7 {
		{
			v, err := r.ReadUUID()
			if err != nil {
				return err
			}
			m.TopicId = v
		}
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if version >= 1 {
		if flexible {
			v, err := r.ReadCompactNullableString()
			if err != nil {
				return err
			}
			m.ErrorMessage = v
		} else {
			v, err := r.ReadNullableString()
			if err != nil {
				return err
			}
			m.ErrorMessage = v
		}
	}
	if version >= 5 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.NumPartitions = v
		}
	}
	if version >= 5 {
		{
			v, err := r.ReadInt16()
			if err != nil {
				return err
			}
			m.ReplicationFactor = v
		}
	}
	if version >= 5 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.Configs = make([]CreateTopicsResponseCreatableTopicConfigs, n)
				for i := 0; i < n; i++ {
					if err := m.Configs[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(func(tag uint64, sub *Reader) error {
			switch tag {
			case 0:
				if !(version >= 5) {
					return nil
				}
				{
					v, err := sub.ReadInt16()
					if err != nil {
						return err
					}
					m.TopicConfigErrorCode = v
				}
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func (m *CreateTopicsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if version >= 2 {
		w.WriteInt32(m.ThrottleTimeMs)
	}
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *CreateTopicsResponseCreatableTopicConfigs) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if version >= 5 {
		if flexible {
			w.WriteCompactString(m.Name)
		} else {
			w.WriteString(m.Name)
		}
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				w.WriteCompactNullableString(m.Value)
			} else {
				w.WriteNullableString(m.Value)
			}
		} else {
			if m.Value == nil {
				return fmt.Errorf("Value: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.Value)
			} else {
				w.WriteString(*m.Value)
			}
		}
	}
	if version >= 5 {
		w.WriteBool(m.ReadOnly)
	}
	if version >= 5 {
		w.WriteInt8(m.ConfigSource)
	}
	if version >= 5 {
		w.WriteBool(m.IsSensitive)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *CreateTopicsResponseCreatableTopicResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	if version >= 7 {
		w.WriteUUID(m.TopicId)
	}
	w.WriteInt16(m.ErrorCode)
	if version >= 1 {
		if flexible {
			w.WriteCompactNullableString(m.ErrorMessage)
		} else {
			w.WriteNullableString(m.ErrorMessage)
		}
	}
	if version >= 5 {
		w.WriteInt32(m.NumPartitions)
	}
	if version >= 5 {
		w.WriteInt16(m.ReplicationFactor)
	}
	if version >= 5 {
		{
			if (version >= 5) && m.Configs == nil {
				if flexible {
					w.WriteCompactArrayLen(-1)
				} else {
					w.WriteArrayLen(-1)
				}
			} else {
				n := len(m.Configs)
				if flexible {
					w.WriteCompactArrayLen(n)
				} else {
					w.WriteArrayLen(n)
				}
				for i := 0; i < n; i++ {
					if err := m.Configs[i].encode(w, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if flexible {
		var tfs []TaggedField
		if version >= 5 {
			sub := NewWriter()
			sub.WriteInt16(m.TopicConfigErrorCode)
			tfs = append(tfs, TaggedField{Tag: 0, Body: sub.Bytes()})
		}
		w.WriteTaggedFields(tfs)
	}
	return nil
}
