// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DeleteAclsResponse struct {
	ThrottleTimeMs int32
	FilterResults  []DeleteAclsResponseDeleteAclsFilterResult
}

type DeleteAclsResponseDeleteAclsFilterResult struct {
	ErrorCode    int16
	ErrorMessage *string
	MatchingAcls []DeleteAclsResponseDeleteAclsMatchingAcl
}

type DeleteAclsResponseDeleteAclsMatchingAcl struct {
	ErrorCode      int16
	ErrorMessage   *string
	ResourceType   int8
	ResourceName   string
	PatternType    int8
	Principal      string
	Host           string
	Operation      int8
	PermissionType int8
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DeleteAclsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DeleteAclsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DeleteAclsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DeleteAclsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DeleteAclsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *DeleteAclsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.FilterResults = make([]DeleteAclsResponseDeleteAclsFilterResult, n)
			for i := 0; i < n; i++ {
				if err := m.FilterResults[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DeleteAclsResponseDeleteAclsFilterResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.MatchingAcls = make([]DeleteAclsResponseDeleteAclsMatchingAcl, n)
			for i := 0; i < n; i++ {
				if err := m.MatchingAcls[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DeleteAclsResponseDeleteAclsMatchingAcl) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.ResourceType = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ResourceName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ResourceName = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt8()
			if err != nil {
				return err
			}
			m.PatternType = v
		}
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Principal = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Principal = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Host = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Host = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.Operation = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.PermissionType = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DeleteAclsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	{
		n := len(m.FilterResults)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.FilterResults[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DeleteAclsResponseDeleteAclsFilterResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	{
		n := len(m.MatchingAcls)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.MatchingAcls[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DeleteAclsResponseDeleteAclsMatchingAcl) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	w.WriteInt8(m.ResourceType)
	if flexible {
		w.WriteCompactString(m.ResourceName)
	} else {
		w.WriteString(m.ResourceName)
	}
	if version >= 1 {
		w.WriteInt8(m.PatternType)
	}
	if flexible {
		w.WriteCompactString(m.Principal)
	} else {
		w.WriteString(m.Principal)
	}
	if flexible {
		w.WriteCompactString(m.Host)
	} else {
		w.WriteString(m.Host)
	}
	w.WriteInt8(m.Operation)
	w.WriteInt8(m.PermissionType)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
