// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DeleteTopicsResponse struct {
	ThrottleTimeMs int32
	Responses      []DeleteTopicsResponseDeletableTopicResult
}

type DeleteTopicsResponseDeletableTopicResult struct {
	Name         *string
	TopicId      [16]byte
	ErrorCode    int16
	ErrorMessage *string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DeleteTopicsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DeleteTopicsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DeleteTopicsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DeleteTopicsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DeleteTopicsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *DeleteTopicsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.ThrottleTimeMs = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Responses = make([]DeleteTopicsResponseDeletableTopicResult, n)
			for i := 0; i < n; i++ {
				if err := m.Responses[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DeleteTopicsResponseDeletableTopicResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 6 {
		if flexible {
			v, err := r.ReadCompactNullableString()
			if err != nil {
				return err
			}
			m.Name = v
		} else {
			v, err := r.ReadNullableString()
			if err != nil {
				return err
			}
			m.Name = v
		}
	} else {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			s := v
			m.Name = &s
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			s := v
			m.Name = &s
		}
	}
	if version >= 6 {
		{
			v, err := r.ReadUUID()
			if err != nil {
				return err
			}
			m.TopicId = v
		}
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.ErrorMessage = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.ErrorMessage = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.ErrorMessage = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.ErrorMessage = &s
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DeleteTopicsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 1 {
		w.WriteInt32(m.ThrottleTimeMs)
	}
	{
		n := len(m.Responses)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Responses[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DeleteTopicsResponseDeletableTopicResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 6 {
		if flexible {
			w.WriteCompactNullableString(m.Name)
		} else {
			w.WriteNullableString(m.Name)
		}
	} else {
		if m.Name == nil {
			return fmt.Errorf("Name: nil at non-nullable version")
		}
		if flexible {
			w.WriteCompactString(*m.Name)
		} else {
			w.WriteString(*m.Name)
		}
	}
	if version >= 6 {
		w.WriteUUID(m.TopicId)
	}
	w.WriteInt16(m.ErrorCode)
	if version >= 5 {
		if version >= 5 {
			if flexible {
				w.WriteCompactNullableString(m.ErrorMessage)
			} else {
				w.WriteNullableString(m.ErrorMessage)
			}
		} else {
			if m.ErrorMessage == nil {
				return fmt.Errorf("ErrorMessage: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.ErrorMessage)
			} else {
				w.WriteString(*m.ErrorMessage)
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
