// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DeleteShareGroupStateRequest struct {
	GroupId string
	Topics  []DeleteShareGroupStateRequestDeleteStateData
}

type DeleteShareGroupStateRequestDeleteStateData struct {
	TopicId    [16]byte
	Partitions []DeleteShareGroupStateRequestPartitionData
}

type DeleteShareGroupStateRequestPartitionData struct {
	Partition int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DeleteShareGroupStateRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DeleteShareGroupStateRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DeleteShareGroupStateRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DeleteShareGroupStateRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DeleteShareGroupStateRequest v%d: %w", version, err)
	}
	return nil
}

func (m *DeleteShareGroupStateRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]DeleteShareGroupStateRequestDeleteStateData, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DeleteShareGroupStateRequestDeleteStateData) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadUUID()
		if err != nil {
			return err
		}
		m.TopicId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]DeleteShareGroupStateRequestPartitionData, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DeleteShareGroupStateRequestPartitionData) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Partition = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DeleteShareGroupStateRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.GroupId)
	} else {
		w.WriteString(m.GroupId)
	}
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DeleteShareGroupStateRequestDeleteStateData) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteUUID(m.TopicId)
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DeleteShareGroupStateRequestPartitionData) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.Partition)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
