// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeTopicPartitionsResponse struct {
	ThrottleTimeMs int32
	Topics         []DescribeTopicPartitionsResponseTopic
	NextCursor     DescribeTopicPartitionsResponseCursor
}

type DescribeTopicPartitionsResponseCursor struct {
	TopicName      string
	PartitionIndex int32
}

type DescribeTopicPartitionsResponsePartition struct {
	ErrorCode              int16
	PartitionIndex         int32
	LeaderId               int32
	LeaderEpoch            int32
	ReplicaNodes           []int32
	IsrNodes               []int32
	EligibleLeaderReplicas []int32
	LastKnownElr           []int32
	OfflineReplicas        []int32
}

type DescribeTopicPartitionsResponseTopic struct {
	ErrorCode                 int16
	Name                      *string
	TopicId                   [16]byte
	IsInternal                bool
	Partitions                []DescribeTopicPartitionsResponsePartition
	TopicAuthorizedOperations int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeTopicPartitionsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeTopicPartitionsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeTopicPartitionsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeTopicPartitionsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeTopicPartitionsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeTopicPartitionsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]DescribeTopicPartitionsResponseTopic, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if err := m.NextCursor.decode(r, version); err != nil {
		return err
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeTopicPartitionsResponseCursor) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.TopicName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.TopicName = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeTopicPartitionsResponsePartition) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderEpoch = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.ReplicaNodes = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.ReplicaNodes[i] = v
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.IsrNodes = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.IsrNodes[i] = v
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.EligibleLeaderReplicas = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.EligibleLeaderReplicas[i] = v
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.LastKnownElr = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.LastKnownElr[i] = v
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.OfflineReplicas = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.OfflineReplicas[i] = v
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeTopicPartitionsResponseTopic) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		v, err := r.ReadUUID()
		if err != nil {
			return err
		}
		m.TopicId = v
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.IsInternal = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]DescribeTopicPartitionsResponsePartition, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.TopicAuthorizedOperations = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeTopicPartitionsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if err := m.NextCursor.encode(w, version); err != nil {
		return err
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeTopicPartitionsResponseCursor) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.TopicName)
	} else {
		w.WriteString(m.TopicName)
	}
	w.WriteInt32(m.PartitionIndex)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeTopicPartitionsResponsePartition) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt32(m.LeaderId)
	w.WriteInt32(m.LeaderEpoch)
	{
		n := len(m.ReplicaNodes)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt32(m.ReplicaNodes[i])
		}
	}
	{
		n := len(m.IsrNodes)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt32(m.IsrNodes[i])
		}
	}
	{
		if m.EligibleLeaderReplicas == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.EligibleLeaderReplicas)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				w.WriteInt32(m.EligibleLeaderReplicas[i])
			}
		}
	}
	{
		if m.LastKnownElr == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.LastKnownElr)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				w.WriteInt32(m.LastKnownElr[i])
			}
		}
	}
	{
		n := len(m.OfflineReplicas)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt32(m.OfflineReplicas[i])
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeTopicPartitionsResponseTopic) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.Name)
	} else {
		w.WriteNullableString(m.Name)
	}
	w.WriteUUID(m.TopicId)
	w.WriteBool(m.IsInternal)
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	w.WriteInt32(m.TopicAuthorizedOperations)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
