// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeClientQuotasResponse struct {
	ThrottleTimeMs int32
	ErrorCode      int16
	ErrorMessage   *string
	Entries        []DescribeClientQuotasResponseEntryData
}

type DescribeClientQuotasResponseEntityData struct {
	EntityType string
	EntityName *string
}

type DescribeClientQuotasResponseEntryData struct {
	Entity []DescribeClientQuotasResponseEntityData
	Values []DescribeClientQuotasResponseValueData
}

type DescribeClientQuotasResponseValueData struct {
	Key   string
	Value float64
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeClientQuotasResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeClientQuotasResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeClientQuotasResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeClientQuotasResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeClientQuotasResponse v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeClientQuotasResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Entries = make([]DescribeClientQuotasResponseEntryData, n)
			for i := 0; i < n; i++ {
				if err := m.Entries[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeClientQuotasResponseEntityData) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.EntityType = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.EntityType = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.EntityName = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.EntityName = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeClientQuotasResponseEntryData) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Entity = make([]DescribeClientQuotasResponseEntityData, n)
			for i := 0; i < n; i++ {
				if err := m.Entity[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Values = make([]DescribeClientQuotasResponseValueData, n)
			for i := 0; i < n; i++ {
				if err := m.Values[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeClientQuotasResponseValueData) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Key = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Key = v
	}
	{
		v, err := r.ReadFloat64()
		if err != nil {
			return err
		}
		m.Value = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeClientQuotasResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	{
		if m.Entries == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.Entries)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.Entries[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeClientQuotasResponseEntityData) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		w.WriteCompactString(m.EntityType)
	} else {
		w.WriteString(m.EntityType)
	}
	if flexible {
		w.WriteCompactNullableString(m.EntityName)
	} else {
		w.WriteNullableString(m.EntityName)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeClientQuotasResponseEntryData) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		n := len(m.Entity)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Entity[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.Values)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Values[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeClientQuotasResponseValueData) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Key)
	} else {
		w.WriteString(m.Key)
	}
	w.WriteFloat64(m.Value)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
