// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeGroupsRequest struct {
	Groups                      []string
	IncludeAuthorizedOperations bool
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeGroupsRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeGroupsRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeGroupsRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeGroupsRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeGroupsRequest v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeGroupsRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Groups = make([]string, n)
			for i := 0; i < n; i++ {
				if flexible {
					v, err := r.ReadCompactString()
					if err != nil {
						return err
					}
					m.Groups[i] = v
				} else {
					v, err := r.ReadString()
					if err != nil {
						return err
					}
					m.Groups[i] = v
				}
			}
		}
	}
	if version >= 3 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.IncludeAuthorizedOperations = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeGroupsRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	{
		n := len(m.Groups)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if flexible {
				w.WriteCompactString(m.Groups[i])
			} else {
				w.WriteString(m.Groups[i])
			}
		}
	}
	if version >= 3 {
		w.WriteBool(m.IncludeAuthorizedOperations)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
