// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeGroupsResponse struct {
	ThrottleTimeMs int32
	Groups         []DescribeGroupsResponseDescribedGroup
}

type DescribeGroupsResponseDescribedGroup struct {
	ErrorCode            int16
	ErrorMessage         *string
	GroupId              string
	GroupState           string
	ProtocolType         string
	ProtocolData         string
	Members              []DescribeGroupsResponseDescribedGroupMember
	AuthorizedOperations int32
}

type DescribeGroupsResponseDescribedGroupMember struct {
	MemberId         string
	GroupInstanceId  *string
	ClientId         string
	ClientHost       string
	MemberMetadata   []byte
	MemberAssignment []byte
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeGroupsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeGroupsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeGroupsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeGroupsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeGroupsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeGroupsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.ThrottleTimeMs = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Groups = make([]DescribeGroupsResponseDescribedGroup, n)
			for i := 0; i < n; i++ {
				if err := m.Groups[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeGroupsResponseDescribedGroup) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if version >= 6 {
		if version >= 6 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.ErrorMessage = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.ErrorMessage = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.ErrorMessage = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.ErrorMessage = &s
			}
		}
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupId = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupState = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupState = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ProtocolType = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ProtocolType = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ProtocolData = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ProtocolData = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Members = make([]DescribeGroupsResponseDescribedGroupMember, n)
			for i := 0; i < n; i++ {
				if err := m.Members[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if version >= 3 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.AuthorizedOperations = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeGroupsResponseDescribedGroupMember) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.MemberId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.MemberId = v
	}
	if version >= 4 {
		if version >= 4 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.GroupInstanceId = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.GroupInstanceId = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.GroupInstanceId = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.GroupInstanceId = &s
			}
		}
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ClientId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ClientId = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ClientHost = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ClientHost = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.MemberMetadata = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.MemberMetadata = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.MemberAssignment = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.MemberAssignment = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeGroupsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if version >= 1 {
		w.WriteInt32(m.ThrottleTimeMs)
	}
	{
		n := len(m.Groups)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Groups[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeGroupsResponseDescribedGroup) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	if version >= 6 {
		if version >= 6 {
			if flexible {
				w.WriteCompactNullableString(m.ErrorMessage)
			} else {
				w.WriteNullableString(m.ErrorMessage)
			}
		} else {
			if m.ErrorMessage == nil {
				return fmt.Errorf("ErrorMessage: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.ErrorMessage)
			} else {
				w.WriteString(*m.ErrorMessage)
			}
		}
	}
	if flexible {
		w.WriteCompactString(m.GroupId)
	} else {
		w.WriteString(m.GroupId)
	}
	if flexible {
		w.WriteCompactString(m.GroupState)
	} else {
		w.WriteString(m.GroupState)
	}
	if flexible {
		w.WriteCompactString(m.ProtocolType)
	} else {
		w.WriteString(m.ProtocolType)
	}
	if flexible {
		w.WriteCompactString(m.ProtocolData)
	} else {
		w.WriteString(m.ProtocolData)
	}
	{
		n := len(m.Members)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Members[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if version >= 3 {
		w.WriteInt32(m.AuthorizedOperations)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeGroupsResponseDescribedGroupMember) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 5
	_ = flexible
	if flexible {
		w.WriteCompactString(m.MemberId)
	} else {
		w.WriteString(m.MemberId)
	}
	if version >= 4 {
		if version >= 4 {
			if flexible {
				w.WriteCompactNullableString(m.GroupInstanceId)
			} else {
				w.WriteNullableString(m.GroupInstanceId)
			}
		} else {
			if m.GroupInstanceId == nil {
				return fmt.Errorf("GroupInstanceId: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.GroupInstanceId)
			} else {
				w.WriteString(*m.GroupInstanceId)
			}
		}
	}
	if flexible {
		w.WriteCompactString(m.ClientId)
	} else {
		w.WriteString(m.ClientId)
	}
	if flexible {
		w.WriteCompactString(m.ClientHost)
	} else {
		w.WriteString(m.ClientHost)
	}
	if flexible {
		w.WriteCompactBytes(m.MemberMetadata)
	} else {
		w.WriteBytes(m.MemberMetadata)
	}
	if flexible {
		w.WriteCompactBytes(m.MemberAssignment)
	} else {
		w.WriteBytes(m.MemberAssignment)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
