// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeConfigsRequest struct {
	Resources            []DescribeConfigsRequestDescribeConfigsResource
	IncludeSynonyms      bool
	IncludeDocumentation bool
}

type DescribeConfigsRequestDescribeConfigsResource struct {
	ResourceType      int8
	ResourceName      string
	ConfigurationKeys []string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeConfigsRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeConfigsRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeConfigsRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeConfigsRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeConfigsRequest v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeConfigsRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Resources = make([]DescribeConfigsRequestDescribeConfigsResource, n)
			for i := 0; i < n; i++ {
				if err := m.Resources[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if version >= 1 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.IncludeSynonyms = v
		}
	}
	if version >= 3 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.IncludeDocumentation = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeConfigsRequestDescribeConfigsResource) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.ResourceType = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ResourceName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ResourceName = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.ConfigurationKeys = make([]string, n)
			for i := 0; i < n; i++ {
				if flexible {
					v, err := r.ReadCompactString()
					if err != nil {
						return err
					}
					m.ConfigurationKeys[i] = v
				} else {
					v, err := r.ReadString()
					if err != nil {
						return err
					}
					m.ConfigurationKeys[i] = v
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeConfigsRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	{
		n := len(m.Resources)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Resources[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if version >= 1 {
		w.WriteBool(m.IncludeSynonyms)
	}
	if version >= 3 {
		w.WriteBool(m.IncludeDocumentation)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeConfigsRequestDescribeConfigsResource) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	w.WriteInt8(m.ResourceType)
	if flexible {
		w.WriteCompactString(m.ResourceName)
	} else {
		w.WriteString(m.ResourceName)
	}
	{
		if m.ConfigurationKeys == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.ConfigurationKeys)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if flexible {
					w.WriteCompactString(m.ConfigurationKeys[i])
				} else {
					w.WriteString(m.ConfigurationKeys[i])
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
