// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeConfigsResponse struct {
	ThrottleTimeMs int32
	Results        []DescribeConfigsResponseDescribeConfigsResult
}

type DescribeConfigsResponseDescribeConfigsResourceResult struct {
	Name          string
	Value         *string
	ReadOnly      bool
	ConfigSource  int8
	IsSensitive   bool
	Synonyms      []DescribeConfigsResponseDescribeConfigsSynonym
	ConfigType    int8
	Documentation *string
}

type DescribeConfigsResponseDescribeConfigsResult struct {
	ErrorCode    int16
	ErrorMessage *string
	ResourceType int8
	ResourceName string
	Configs      []DescribeConfigsResponseDescribeConfigsResourceResult
}

type DescribeConfigsResponseDescribeConfigsSynonym struct {
	Name   string
	Value  *string
	Source int8
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeConfigsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeConfigsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeConfigsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeConfigsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeConfigsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeConfigsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Results = make([]DescribeConfigsResponseDescribeConfigsResult, n)
			for i := 0; i < n; i++ {
				if err := m.Results[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeConfigsResponseDescribeConfigsResourceResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.Value = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.Value = v
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.ReadOnly = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt8()
			if err != nil {
				return err
			}
			m.ConfigSource = v
		}
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.IsSensitive = v
	}
	if version >= 1 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.Synonyms = make([]DescribeConfigsResponseDescribeConfigsSynonym, n)
				for i := 0; i < n; i++ {
					if err := m.Synonyms[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if version >= 3 {
		{
			v, err := r.ReadInt8()
			if err != nil {
				return err
			}
			m.ConfigType = v
		}
	}
	if version >= 3 {
		if flexible {
			v, err := r.ReadCompactNullableString()
			if err != nil {
				return err
			}
			m.Documentation = v
		} else {
			v, err := r.ReadNullableString()
			if err != nil {
				return err
			}
			m.Documentation = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeConfigsResponseDescribeConfigsResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.ResourceType = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ResourceName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ResourceName = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Configs = make([]DescribeConfigsResponseDescribeConfigsResourceResult, n)
			for i := 0; i < n; i++ {
				if err := m.Configs[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeConfigsResponseDescribeConfigsSynonym) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 1 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Name = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Name = v
		}
	}
	if version >= 1 {
		if flexible {
			v, err := r.ReadCompactNullableString()
			if err != nil {
				return err
			}
			m.Value = v
		} else {
			v, err := r.ReadNullableString()
			if err != nil {
				return err
			}
			m.Value = v
		}
	}
	if version >= 1 {
		{
			v, err := r.ReadInt8()
			if err != nil {
				return err
			}
			m.Source = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeConfigsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	{
		n := len(m.Results)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Results[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeConfigsResponseDescribeConfigsResourceResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	if flexible {
		w.WriteCompactNullableString(m.Value)
	} else {
		w.WriteNullableString(m.Value)
	}
	w.WriteBool(m.ReadOnly)
	if version >= 1 {
		w.WriteInt8(m.ConfigSource)
	}
	w.WriteBool(m.IsSensitive)
	if version >= 1 {
		{
			n := len(m.Synonyms)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.Synonyms[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if version >= 3 {
		w.WriteInt8(m.ConfigType)
	}
	if version >= 3 {
		if flexible {
			w.WriteCompactNullableString(m.Documentation)
		} else {
			w.WriteNullableString(m.Documentation)
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeConfigsResponseDescribeConfigsResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	w.WriteInt8(m.ResourceType)
	if flexible {
		w.WriteCompactString(m.ResourceName)
	} else {
		w.WriteString(m.ResourceName)
	}
	{
		n := len(m.Configs)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Configs[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeConfigsResponseDescribeConfigsSynonym) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 1 {
		if flexible {
			w.WriteCompactString(m.Name)
		} else {
			w.WriteString(m.Name)
		}
	}
	if version >= 1 {
		if flexible {
			w.WriteCompactNullableString(m.Value)
		} else {
			w.WriteNullableString(m.Value)
		}
	}
	if version >= 1 {
		w.WriteInt8(m.Source)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
