// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeLogDirsResponse struct {
	ThrottleTimeMs int32
	ErrorCode      int16
	Results        []DescribeLogDirsResponseDescribeLogDirsResult
}

type DescribeLogDirsResponseDescribeLogDirsPartition struct {
	PartitionIndex int32
	PartitionSize  int64
	OffsetLag      int64
	IsFutureKey    bool
}

type DescribeLogDirsResponseDescribeLogDirsResult struct {
	ErrorCode   int16
	LogDir      string
	Topics      []DescribeLogDirsResponseDescribeLogDirsTopic
	TotalBytes  int64
	UsableBytes int64
	IsCordoned  bool
}

type DescribeLogDirsResponseDescribeLogDirsTopic struct {
	Name       string
	Partitions []DescribeLogDirsResponseDescribeLogDirsPartition
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeLogDirsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeLogDirsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeLogDirsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeLogDirsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeLogDirsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeLogDirsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	if version >= 3 {
		{
			v, err := r.ReadInt16()
			if err != nil {
				return err
			}
			m.ErrorCode = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Results = make([]DescribeLogDirsResponseDescribeLogDirsResult, n)
			for i := 0; i < n; i++ {
				if err := m.Results[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeLogDirsResponseDescribeLogDirsPartition) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.PartitionSize = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.OffsetLag = v
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.IsFutureKey = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeLogDirsResponseDescribeLogDirsResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.LogDir = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.LogDir = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]DescribeLogDirsResponseDescribeLogDirsTopic, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if version >= 4 {
		{
			v, err := r.ReadInt64()
			if err != nil {
				return err
			}
			m.TotalBytes = v
		}
	}
	if version >= 4 {
		{
			v, err := r.ReadInt64()
			if err != nil {
				return err
			}
			m.UsableBytes = v
		}
	}
	if version >= 5 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.IsCordoned = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeLogDirsResponseDescribeLogDirsTopic) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]DescribeLogDirsResponseDescribeLogDirsPartition, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeLogDirsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	if version >= 3 {
		w.WriteInt16(m.ErrorCode)
	}
	{
		n := len(m.Results)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Results[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeLogDirsResponseDescribeLogDirsPartition) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt64(m.PartitionSize)
	w.WriteInt64(m.OffsetLag)
	w.WriteBool(m.IsFutureKey)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeLogDirsResponseDescribeLogDirsResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactString(m.LogDir)
	} else {
		w.WriteString(m.LogDir)
	}
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if version >= 4 {
		w.WriteInt64(m.TotalBytes)
	}
	if version >= 4 {
		w.WriteInt64(m.UsableBytes)
	}
	if version >= 5 {
		w.WriteBool(m.IsCordoned)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeLogDirsResponseDescribeLogDirsTopic) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
