// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeClusterRequest struct {
	IncludeClusterAuthorizedOperations bool
	EndpointType                       int8
	IncludeFencedBrokers               bool
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeClusterRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeClusterRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeClusterRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeClusterRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeClusterRequest v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeClusterRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.IncludeClusterAuthorizedOperations = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt8()
			if err != nil {
				return err
			}
			m.EndpointType = v
		}
	}
	if version >= 2 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.IncludeFencedBrokers = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeClusterRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteBool(m.IncludeClusterAuthorizedOperations)
	if version >= 1 {
		w.WriteInt8(m.EndpointType)
	}
	if version >= 2 {
		w.WriteBool(m.IncludeFencedBrokers)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
