// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeClientQuotasRequest struct {
	Components []DescribeClientQuotasRequestComponentData
	Strict     bool
}

type DescribeClientQuotasRequestComponentData struct {
	EntityType string
	MatchType  int8
	Match      *string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeClientQuotasRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeClientQuotasRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeClientQuotasRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeClientQuotasRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeClientQuotasRequest v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeClientQuotasRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Components = make([]DescribeClientQuotasRequestComponentData, n)
			for i := 0; i < n; i++ {
				if err := m.Components[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.Strict = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeClientQuotasRequestComponentData) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.EntityType = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.EntityType = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.MatchType = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.Match = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.Match = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeClientQuotasRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		n := len(m.Components)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Components[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	w.WriteBool(m.Strict)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeClientQuotasRequestComponentData) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		w.WriteCompactString(m.EntityType)
	} else {
		w.WriteString(m.EntityType)
	}
	w.WriteInt8(m.MatchType)
	if flexible {
		w.WriteCompactNullableString(m.Match)
	} else {
		w.WriteNullableString(m.Match)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
