// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type DescribeDelegationTokenRequest struct {
	Owners []DescribeDelegationTokenRequestDescribeDelegationTokenOwner
}

type DescribeDelegationTokenRequestDescribeDelegationTokenOwner struct {
	PrincipalType string
	PrincipalName string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *DescribeDelegationTokenRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("DescribeDelegationTokenRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("DescribeDelegationTokenRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *DescribeDelegationTokenRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("DescribeDelegationTokenRequest v%d: %w", version, err)
	}
	return nil
}

func (m *DescribeDelegationTokenRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Owners = make([]DescribeDelegationTokenRequestDescribeDelegationTokenOwner, n)
			for i := 0; i < n; i++ {
				if err := m.Owners[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeDelegationTokenRequestDescribeDelegationTokenOwner) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.PrincipalType = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.PrincipalType = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.PrincipalName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.PrincipalName = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *DescribeDelegationTokenRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		if m.Owners == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.Owners)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.Owners[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *DescribeDelegationTokenRequestDescribeDelegationTokenOwner) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	if flexible {
		w.WriteCompactString(m.PrincipalType)
	} else {
		w.WriteString(m.PrincipalType)
	}
	if flexible {
		w.WriteCompactString(m.PrincipalName)
	} else {
		w.WriteString(m.PrincipalName)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
