// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import "fmt"

// Message is implemented by every generated request/response struct.
type Message interface {
	Decode(r *Reader, version int16) error
	Encode(w *Writer, version int16) error
}

// UnmarshalRequest decodes a Kafka request body from r (positioned after the request/response
// header) into the appropriate generated struct, dispatched on apiKey.
func UnmarshalRequest(r *Reader, apiKey, apiVersion int16) (Message, error) {
	var m Message
	switch apiKey {
	case 0:
		m = &ProduceRequest{}
	case 1:
		m = &FetchRequest{}
	case 2:
		m = &ListOffsetsRequest{}
	case 3:
		m = &MetadataRequest{}
	case 8:
		m = &OffsetCommitRequest{}
	case 9:
		m = &OffsetFetchRequest{}
	case 10:
		m = &FindCoordinatorRequest{}
	case 11:
		m = &JoinGroupRequest{}
	case 12:
		m = &HeartbeatRequest{}
	case 13:
		m = &LeaveGroupRequest{}
	case 14:
		m = &SyncGroupRequest{}
	case 15:
		m = &DescribeGroupsRequest{}
	case 16:
		m = &ListGroupsRequest{}
	case 17:
		m = &SaslHandshakeRequest{}
	case 18:
		m = &ApiVersionsRequest{}
	case 19:
		m = &CreateTopicsRequest{}
	case 20:
		m = &DeleteTopicsRequest{}
	case 21:
		m = &DeleteRecordsRequest{}
	case 22:
		m = &InitProducerIdRequest{}
	case 23:
		m = &OffsetForLeaderEpochRequest{}
	case 24:
		m = &AddPartitionsToTxnRequest{}
	case 25:
		m = &AddOffsetsToTxnRequest{}
	case 26:
		m = &EndTxnRequest{}
	case 27:
		m = &WriteTxnMarkersRequest{}
	case 28:
		m = &TxnOffsetCommitRequest{}
	case 29:
		m = &DescribeAclsRequest{}
	case 30:
		m = &CreateAclsRequest{}
	case 31:
		m = &DeleteAclsRequest{}
	case 32:
		m = &DescribeConfigsRequest{}
	case 33:
		m = &AlterConfigsRequest{}
	case 34:
		m = &AlterReplicaLogDirsRequest{}
	case 35:
		m = &DescribeLogDirsRequest{}
	case 36:
		m = &SaslAuthenticateRequest{}
	case 37:
		m = &CreatePartitionsRequest{}
	case 38:
		m = &CreateDelegationTokenRequest{}
	case 39:
		m = &RenewDelegationTokenRequest{}
	case 40:
		m = &ExpireDelegationTokenRequest{}
	case 41:
		m = &DescribeDelegationTokenRequest{}
	case 42:
		m = &DeleteGroupsRequest{}
	case 43:
		m = &ElectLeadersRequest{}
	case 44:
		m = &IncrementalAlterConfigsRequest{}
	case 45:
		m = &AlterPartitionReassignmentsRequest{}
	case 46:
		m = &ListPartitionReassignmentsRequest{}
	case 47:
		m = &OffsetDeleteRequest{}
	case 48:
		m = &DescribeClientQuotasRequest{}
	case 49:
		m = &AlterClientQuotasRequest{}
	case 50:
		m = &DescribeUserScramCredentialsRequest{}
	case 51:
		m = &AlterUserScramCredentialsRequest{}
	case 52:
		m = &VoteRequest{}
	case 53:
		m = &BeginQuorumEpochRequest{}
	case 54:
		m = &EndQuorumEpochRequest{}
	case 55:
		m = &DescribeQuorumRequest{}
	case 56:
		m = &AlterPartitionRequest{}
	case 57:
		m = &UpdateFeaturesRequest{}
	case 58:
		m = &EnvelopeRequest{}
	case 59:
		m = &FetchSnapshotRequest{}
	case 60:
		m = &DescribeClusterRequest{}
	case 61:
		m = &DescribeProducersRequest{}
	case 62:
		m = &BrokerRegistrationRequest{}
	case 63:
		m = &BrokerHeartbeatRequest{}
	case 64:
		m = &UnregisterBrokerRequest{}
	case 65:
		m = &DescribeTransactionsRequest{}
	case 66:
		m = &ListTransactionsRequest{}
	case 67:
		m = &AllocateProducerIdsRequest{}
	case 68:
		m = &ConsumerGroupHeartbeatRequest{}
	case 69:
		m = &ConsumerGroupDescribeRequest{}
	case 70:
		m = &ControllerRegistrationRequest{}
	case 71:
		m = &GetTelemetrySubscriptionsRequest{}
	case 72:
		m = &PushTelemetryRequest{}
	case 73:
		m = &AssignReplicasToDirsRequest{}
	case 74:
		m = &ListConfigResourcesRequest{}
	case 75:
		m = &DescribeTopicPartitionsRequest{}
	case 76:
		m = &ShareGroupHeartbeatRequest{}
	case 77:
		m = &ShareGroupDescribeRequest{}
	case 78:
		m = &ShareFetchRequest{}
	case 79:
		m = &ShareAcknowledgeRequest{}
	case 80:
		m = &AddRaftVoterRequest{}
	case 81:
		m = &RemoveRaftVoterRequest{}
	case 82:
		m = &UpdateRaftVoterRequest{}
	case 83:
		m = &InitializeShareGroupStateRequest{}
	case 84:
		m = &ReadShareGroupStateRequest{}
	case 85:
		m = &WriteShareGroupStateRequest{}
	case 86:
		m = &DeleteShareGroupStateRequest{}
	case 87:
		m = &ReadShareGroupStateSummaryRequest{}
	case 88:
		m = &StreamsGroupHeartbeatRequest{}
	case 89:
		m = &StreamsGroupDescribeRequest{}
	case 90:
		m = &DescribeShareGroupOffsetsRequest{}
	case 91:
		m = &AlterShareGroupOffsetsRequest{}
	case 92:
		m = &DeleteShareGroupOffsetsRequest{}
	default:
		return nil, fmt.Errorf("kafkaproto: unsupported request apiKey %d", apiKey)
	}
	if err := m.Decode(r, apiVersion); err != nil {
		return nil, err
	}
	return m, nil
}

// UnmarshalResponse decodes a Kafka response body from r (positioned after the request/response
// header) into the appropriate generated struct, dispatched on apiKey.
func UnmarshalResponse(r *Reader, apiKey, apiVersion int16) (Message, error) {
	var m Message
	switch apiKey {
	case 0:
		m = &ProduceResponse{}
	case 1:
		m = &FetchResponse{}
	case 2:
		m = &ListOffsetsResponse{}
	case 3:
		m = &MetadataResponse{}
	case 8:
		m = &OffsetCommitResponse{}
	case 9:
		m = &OffsetFetchResponse{}
	case 10:
		m = &FindCoordinatorResponse{}
	case 11:
		m = &JoinGroupResponse{}
	case 12:
		m = &HeartbeatResponse{}
	case 13:
		m = &LeaveGroupResponse{}
	case 14:
		m = &SyncGroupResponse{}
	case 15:
		m = &DescribeGroupsResponse{}
	case 16:
		m = &ListGroupsResponse{}
	case 17:
		m = &SaslHandshakeResponse{}
	case 18:
		m = &ApiVersionsResponse{}
	case 19:
		m = &CreateTopicsResponse{}
	case 20:
		m = &DeleteTopicsResponse{}
	case 21:
		m = &DeleteRecordsResponse{}
	case 22:
		m = &InitProducerIdResponse{}
	case 23:
		m = &OffsetForLeaderEpochResponse{}
	case 24:
		m = &AddPartitionsToTxnResponse{}
	case 25:
		m = &AddOffsetsToTxnResponse{}
	case 26:
		m = &EndTxnResponse{}
	case 27:
		m = &WriteTxnMarkersResponse{}
	case 28:
		m = &TxnOffsetCommitResponse{}
	case 29:
		m = &DescribeAclsResponse{}
	case 30:
		m = &CreateAclsResponse{}
	case 31:
		m = &DeleteAclsResponse{}
	case 32:
		m = &DescribeConfigsResponse{}
	case 33:
		m = &AlterConfigsResponse{}
	case 34:
		m = &AlterReplicaLogDirsResponse{}
	case 35:
		m = &DescribeLogDirsResponse{}
	case 36:
		m = &SaslAuthenticateResponse{}
	case 37:
		m = &CreatePartitionsResponse{}
	case 38:
		m = &CreateDelegationTokenResponse{}
	case 39:
		m = &RenewDelegationTokenResponse{}
	case 40:
		m = &ExpireDelegationTokenResponse{}
	case 41:
		m = &DescribeDelegationTokenResponse{}
	case 42:
		m = &DeleteGroupsResponse{}
	case 43:
		m = &ElectLeadersResponse{}
	case 44:
		m = &IncrementalAlterConfigsResponse{}
	case 45:
		m = &AlterPartitionReassignmentsResponse{}
	case 46:
		m = &ListPartitionReassignmentsResponse{}
	case 47:
		m = &OffsetDeleteResponse{}
	case 48:
		m = &DescribeClientQuotasResponse{}
	case 49:
		m = &AlterClientQuotasResponse{}
	case 50:
		m = &DescribeUserScramCredentialsResponse{}
	case 51:
		m = &AlterUserScramCredentialsResponse{}
	case 52:
		m = &VoteResponse{}
	case 53:
		m = &BeginQuorumEpochResponse{}
	case 54:
		m = &EndQuorumEpochResponse{}
	case 55:
		m = &DescribeQuorumResponse{}
	case 56:
		m = &AlterPartitionResponse{}
	case 57:
		m = &UpdateFeaturesResponse{}
	case 58:
		m = &EnvelopeResponse{}
	case 59:
		m = &FetchSnapshotResponse{}
	case 60:
		m = &DescribeClusterResponse{}
	case 61:
		m = &DescribeProducersResponse{}
	case 62:
		m = &BrokerRegistrationResponse{}
	case 63:
		m = &BrokerHeartbeatResponse{}
	case 64:
		m = &UnregisterBrokerResponse{}
	case 65:
		m = &DescribeTransactionsResponse{}
	case 66:
		m = &ListTransactionsResponse{}
	case 67:
		m = &AllocateProducerIdsResponse{}
	case 68:
		m = &ConsumerGroupHeartbeatResponse{}
	case 69:
		m = &ConsumerGroupDescribeResponse{}
	case 70:
		m = &ControllerRegistrationResponse{}
	case 71:
		m = &GetTelemetrySubscriptionsResponse{}
	case 72:
		m = &PushTelemetryResponse{}
	case 73:
		m = &AssignReplicasToDirsResponse{}
	case 74:
		m = &ListConfigResourcesResponse{}
	case 75:
		m = &DescribeTopicPartitionsResponse{}
	case 76:
		m = &ShareGroupHeartbeatResponse{}
	case 77:
		m = &ShareGroupDescribeResponse{}
	case 78:
		m = &ShareFetchResponse{}
	case 79:
		m = &ShareAcknowledgeResponse{}
	case 80:
		m = &AddRaftVoterResponse{}
	case 81:
		m = &RemoveRaftVoterResponse{}
	case 82:
		m = &UpdateRaftVoterResponse{}
	case 83:
		m = &InitializeShareGroupStateResponse{}
	case 84:
		m = &ReadShareGroupStateResponse{}
	case 85:
		m = &WriteShareGroupStateResponse{}
	case 86:
		m = &DeleteShareGroupStateResponse{}
	case 87:
		m = &ReadShareGroupStateSummaryResponse{}
	case 88:
		m = &StreamsGroupHeartbeatResponse{}
	case 89:
		m = &StreamsGroupDescribeResponse{}
	case 90:
		m = &DescribeShareGroupOffsetsResponse{}
	case 91:
		m = &AlterShareGroupOffsetsResponse{}
	case 92:
		m = &DeleteShareGroupOffsetsResponse{}
	default:
		return nil, fmt.Errorf("kafkaproto: unsupported response apiKey %d", apiKey)
	}
	if err := m.Decode(r, apiVersion); err != nil {
		return nil, err
	}
	return m, nil
}
