// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import "fmt"

// Message is implemented by every generated request/response struct.
type Message interface {
	Decode(r *Reader, version int16) error
	Encode(w *Writer, version int16) error
}

// UnmarshalRequest decodes a Kafka request body from r (positioned after the request/response
// header) into the appropriate generated struct, dispatched on apiKey.
func UnmarshalRequest(r *Reader, apiKey, apiVersion int16) (Message, error) {
	var m Message
	switch apiKey {
	case 0:
		m = &ProduceRequest{}
	case 1:
		m = &FetchRequest{}
	case 2:
		m = &ListOffsetsRequest{}
	case 3:
		m = &MetadataRequest{}
	case 8:
		m = &OffsetCommitRequest{}
	case 9:
		m = &OffsetFetchRequest{}
	case 10:
		m = &FindCoordinatorRequest{}
	case 11:
		m = &JoinGroupRequest{}
	case 12:
		m = &HeartbeatRequest{}
	case 13:
		m = &LeaveGroupRequest{}
	case 14:
		m = &SyncGroupRequest{}
	case 15:
		m = &DescribeGroupsRequest{}
	case 16:
		m = &ListGroupsRequest{}
	case 17:
		m = &SaslHandshakeRequest{}
	case 18:
		m = &ApiVersionsRequest{}
	case 19:
		m = &CreateTopicsRequest{}
	case 20:
		m = &DeleteTopicsRequest{}
	case 21:
		m = &DeleteRecordsRequest{}
	case 22:
		m = &InitProducerIdRequest{}
	case 23:
		m = &OffsetForLeaderEpochRequest{}
	case 24:
		m = &AddPartitionsToTxnRequest{}
	case 25:
		m = &AddOffsetsToTxnRequest{}
	case 26:
		m = &EndTxnRequest{}
	case 27:
		m = &WriteTxnMarkersRequest{}
	case 28:
		m = &TxnOffsetCommitRequest{}
	case 29:
		m = &DescribeAclsRequest{}
	case 30:
		m = &CreateAclsRequest{}
	case 31:
		m = &DeleteAclsRequest{}
	case 32:
		m = &DescribeConfigsRequest{}
	case 33:
		m = &AlterConfigsRequest{}
	case 34:
		m = &AlterReplicaLogDirsRequest{}
	case 35:
		m = &DescribeLogDirsRequest{}
	case 36:
		m = &SaslAuthenticateRequest{}
	case 37:
		m = &CreatePartitionsRequest{}
	case 38:
		m = &CreateDelegationTokenRequest{}
	case 39:
		m = &RenewDelegationTokenRequest{}
	case 40:
		m = &ExpireDelegationTokenRequest{}
	case 41:
		m = &DescribeDelegationTokenRequest{}
	case 42:
		m = &DeleteGroupsRequest{}
	case 43:
		m = &ElectLeadersRequest{}
	case 44:
		m = &IncrementalAlterConfigsRequest{}
	case 45:
		m = &AlterPartitionReassignmentsRequest{}
	case 46:
		m = &ListPartitionReassignmentsRequest{}
	case 47:
		m = &OffsetDeleteRequest{}
	case 48:
		m = &DescribeClientQuotasRequest{}
	case 49:
		m = &AlterClientQuotasRequest{}
	case 50:
		m = &DescribeUserScramCredentialsRequest{}
	case 51:
		m = &AlterUserScramCredentialsRequest{}
	case 52:
		m = &VoteRequest{}
	case 53:
		m = &BeginQuorumEpochRequest{}
	case 54:
		m = &EndQuorumEpochRequest{}
	case 55:
		m = &DescribeQuorumRequest{}
	case 56:
		m = &AlterPartitionRequest{}
	case 57:
		m = &UpdateFeaturesRequest{}
	case 58:
		m = &EnvelopeRequest{}
	case 59:
		m = &FetchSnapshotRequest{}
	case 60:
		m = &DescribeClusterRequest{}
	case 61:
		m = &DescribeProducersRequest{}
	case 62:
		m = &BrokerRegistrationRequest{}
	case 63:
		m = &BrokerHeartbeatRequest{}
	case 64:
		m = &UnregisterBrokerRequest{}
	case 65:
		m = &DescribeTransactionsRequest{}
	case 66:
		m = &ListTransactionsRequest{}
	case 67:
		m = &AllocateProducerIdsRequest{}
	case 68:
		m = &ConsumerGroupHeartbeatRequest{}
	case 69:
		m = &ConsumerGroupDescribeRequest{}
	case 70:
		m = &ControllerRegistrationRequest{}
	case 71:
		m = &GetTelemetrySubscriptionsRequest{}
	case 72:
		m = &PushTelemetryRequest{}
	case 73:
		m = &AssignReplicasToDirsRequest{}
	case 74:
		m = &ListConfigResourcesRequest{}
	case 75:
		m = &DescribeTopicPartitionsRequest{}
	case 76:
		m = &ShareGroupHeartbeatRequest{}
	case 77:
		m = &ShareGroupDescribeRequest{}
	case 78:
		m = &ShareFetchRequest{}
	case 79:
		m = &ShareAcknowledgeRequest{}
	case 80:
		m = &AddRaftVoterRequest{}
	case 81:
		m = &RemoveRaftVoterRequest{}
	case 82:
		m = &UpdateRaftVoterRequest{}
	case 83:
		m = &InitializeShareGroupStateRequest{}
	case 84:
		m = &ReadShareGroupStateRequest{}
	case 85:
		m = &WriteShareGroupStateRequest{}
	case 86:
		m = &DeleteShareGroupStateRequest{}
	case 87:
		m = &ReadShareGroupStateSummaryRequest{}
	case 88:
		m = &StreamsGroupHeartbeatRequest{}
	case 89:
		m = &StreamsGroupDescribeRequest{}
	case 90:
		m = &DescribeShareGroupOffsetsRequest{}
	case 91:
		m = &AlterShareGroupOffsetsRequest{}
	case 92:
		m = &DeleteShareGroupOffsetsRequest{}
	default:
		return nil, fmt.Errorf("kafkaproto: unsupported request apiKey %d", apiKey)
	}
	if err := m.Decode(r, apiVersion); err != nil {
		return nil, err
	}
	return m, nil
}

// UnmarshalResponse decodes a Kafka response body from r (positioned after the request/response
// header) into the appropriate generated struct, dispatched on apiKey.
func UnmarshalResponse(r *Reader, apiKey, apiVersion int16) (Message, error) {
	var m Message
	switch apiKey {
	case 0:
		m = &ProduceResponse{}
	case 1:
		m = &FetchResponse{}
	case 2:
		m = &ListOffsetsResponse{}
	case 3:
		m = &MetadataResponse{}
	case 8:
		m = &OffsetCommitResponse{}
	case 9:
		m = &OffsetFetchResponse{}
	case 10:
		m = &FindCoordinatorResponse{}
	case 11:
		m = &JoinGroupResponse{}
	case 12:
		m = &HeartbeatResponse{}
	case 13:
		m = &LeaveGroupResponse{}
	case 14:
		m = &SyncGroupResponse{}
	case 15:
		m = &DescribeGroupsResponse{}
	case 16:
		m = &ListGroupsResponse{}
	case 17:
		m = &SaslHandshakeResponse{}
	case 18:
		m = &ApiVersionsResponse{}
	case 19:
		m = &CreateTopicsResponse{}
	case 20:
		m = &DeleteTopicsResponse{}
	case 21:
		m = &DeleteRecordsResponse{}
	case 22:
		m = &InitProducerIdResponse{}
	case 23:
		m = &OffsetForLeaderEpochResponse{}
	case 24:
		m = &AddPartitionsToTxnResponse{}
	case 25:
		m = &AddOffsetsToTxnResponse{}
	case 26:
		m = &EndTxnResponse{}
	case 27:
		m = &WriteTxnMarkersResponse{}
	case 28:
		m = &TxnOffsetCommitResponse{}
	case 29:
		m = &DescribeAclsResponse{}
	case 30:
		m = &CreateAclsResponse{}
	case 31:
		m = &DeleteAclsResponse{}
	case 32:
		m = &DescribeConfigsResponse{}
	case 33:
		m = &AlterConfigsResponse{}
	case 34:
		m = &AlterReplicaLogDirsResponse{}
	case 35:
		m = &DescribeLogDirsResponse{}
	case 36:
		m = &SaslAuthenticateResponse{}
	case 37:
		m = &CreatePartitionsResponse{}
	case 38:
		m = &CreateDelegationTokenResponse{}
	case 39:
		m = &RenewDelegationTokenResponse{}
	case 40:
		m = &ExpireDelegationTokenResponse{}
	case 41:
		m = &DescribeDelegationTokenResponse{}
	case 42:
		m = &DeleteGroupsResponse{}
	case 43:
		m = &ElectLeadersResponse{}
	case 44:
		m = &IncrementalAlterConfigsResponse{}
	case 45:
		m = &AlterPartitionReassignmentsResponse{}
	case 46:
		m = &ListPartitionReassignmentsResponse{}
	case 47:
		m = &OffsetDeleteResponse{}
	case 48:
		m = &DescribeClientQuotasResponse{}
	case 49:
		m = &AlterClientQuotasResponse{}
	case 50:
		m = &DescribeUserScramCredentialsResponse{}
	case 51:
		m = &AlterUserScramCredentialsResponse{}
	case 52:
		m = &VoteResponse{}
	case 53:
		m = &BeginQuorumEpochResponse{}
	case 54:
		m = &EndQuorumEpochResponse{}
	case 55:
		m = &DescribeQuorumResponse{}
	case 56:
		m = &AlterPartitionResponse{}
	case 57:
		m = &UpdateFeaturesResponse{}
	case 58:
		m = &EnvelopeResponse{}
	case 59:
		m = &FetchSnapshotResponse{}
	case 60:
		m = &DescribeClusterResponse{}
	case 61:
		m = &DescribeProducersResponse{}
	case 62:
		m = &BrokerRegistrationResponse{}
	case 63:
		m = &BrokerHeartbeatResponse{}
	case 64:
		m = &UnregisterBrokerResponse{}
	case 65:
		m = &DescribeTransactionsResponse{}
	case 66:
		m = &ListTransactionsResponse{}
	case 67:
		m = &AllocateProducerIdsResponse{}
	case 68:
		m = &ConsumerGroupHeartbeatResponse{}
	case 69:
		m = &ConsumerGroupDescribeResponse{}
	case 70:
		m = &ControllerRegistrationResponse{}
	case 71:
		m = &GetTelemetrySubscriptionsResponse{}
	case 72:
		m = &PushTelemetryResponse{}
	case 73:
		m = &AssignReplicasToDirsResponse{}
	case 74:
		m = &ListConfigResourcesResponse{}
	case 75:
		m = &DescribeTopicPartitionsResponse{}
	case 76:
		m = &ShareGroupHeartbeatResponse{}
	case 77:
		m = &ShareGroupDescribeResponse{}
	case 78:
		m = &ShareFetchResponse{}
	case 79:
		m = &ShareAcknowledgeResponse{}
	case 80:
		m = &AddRaftVoterResponse{}
	case 81:
		m = &RemoveRaftVoterResponse{}
	case 82:
		m = &UpdateRaftVoterResponse{}
	case 83:
		m = &InitializeShareGroupStateResponse{}
	case 84:
		m = &ReadShareGroupStateResponse{}
	case 85:
		m = &WriteShareGroupStateResponse{}
	case 86:
		m = &DeleteShareGroupStateResponse{}
	case 87:
		m = &ReadShareGroupStateSummaryResponse{}
	case 88:
		m = &StreamsGroupHeartbeatResponse{}
	case 89:
		m = &StreamsGroupDescribeResponse{}
	case 90:
		m = &DescribeShareGroupOffsetsResponse{}
	case 91:
		m = &AlterShareGroupOffsetsResponse{}
	case 92:
		m = &DeleteShareGroupOffsetsResponse{}
	default:
		return nil, fmt.Errorf("kafkaproto: unsupported response apiKey %d", apiKey)
	}
	if err := m.Decode(r, apiVersion); err != nil {
		return nil, err
	}
	return m, nil
}

// ReadRequestHeader decodes a Kafka request header. For flexible (apiKey,
// apiVersion) combinations it also consumes the trailing tagged-fields count,
// leaving r positioned at the start of the request body.
func ReadRequestHeader(r *Reader) (apiKey int16, apiVersion int16, corrID int32, clientID *string, err error) {
	apiKey, err = r.ReadInt16()
	if err != nil {
		return
	}
	apiVersion, err = r.ReadInt16()
	if err != nil {
		return
	}
	corrID, err = r.ReadInt32()
	if err != nil {
		return
	}
	clientID, err = r.ReadNullableString()
	if err != nil {
		return
	}
	if requestHeaderFlexible(apiKey, apiVersion) {
		if err = r.ReadTaggedFields(nil); err != nil {
			return
		}
	}
	return
}

// WriteRequestHeader encodes a Kafka request header (apiKey, apiVersion,
// correlation id, client id). For flexible (apiKey, apiVersion) combinations
// it also writes an empty tagged-fields block.
func WriteRequestHeader(w *Writer, apiKey int16, apiVersion int16, corrID int32, clientID *string) {
	w.WriteInt16(apiKey)
	w.WriteInt16(apiVersion)
	w.WriteInt32(corrID)
	w.WriteNullableString(clientID)
	if requestHeaderFlexible(apiKey, apiVersion) {
		w.WriteTaggedFields(nil)
	}
}

func requestHeaderFlexible(apiKey, apiVersion int16) bool {
	_ = apiVersion
	switch apiKey {
	case 0: // ProduceRequest
		return apiVersion >= 9
	case 1: // FetchRequest
		return apiVersion >= 12
	case 2: // ListOffsetsRequest
		return apiVersion >= 6
	case 3: // MetadataRequest
		return apiVersion >= 9
	case 8: // OffsetCommitRequest
		return apiVersion >= 8
	case 9: // OffsetFetchRequest
		return apiVersion >= 6
	case 10: // FindCoordinatorRequest
		return apiVersion >= 3
	case 11: // JoinGroupRequest
		return apiVersion >= 6
	case 12: // HeartbeatRequest
		return apiVersion >= 4
	case 13: // LeaveGroupRequest
		return apiVersion >= 4
	case 14: // SyncGroupRequest
		return apiVersion >= 4
	case 15: // DescribeGroupsRequest
		return apiVersion >= 5
	case 16: // ListGroupsRequest
		return apiVersion >= 3
	case 17: // SaslHandshakeRequest
		return false
	case 18: // ApiVersionsRequest
		return apiVersion >= 3
	case 19: // CreateTopicsRequest
		return apiVersion >= 5
	case 20: // DeleteTopicsRequest
		return apiVersion >= 4
	case 21: // DeleteRecordsRequest
		return apiVersion >= 2
	case 22: // InitProducerIdRequest
		return apiVersion >= 2
	case 23: // OffsetForLeaderEpochRequest
		return apiVersion >= 4
	case 24: // AddPartitionsToTxnRequest
		return apiVersion >= 3
	case 25: // AddOffsetsToTxnRequest
		return apiVersion >= 3
	case 26: // EndTxnRequest
		return apiVersion >= 3
	case 27: // WriteTxnMarkersRequest
		return apiVersion >= 1
	case 28: // TxnOffsetCommitRequest
		return apiVersion >= 3
	case 29: // DescribeAclsRequest
		return apiVersion >= 2
	case 30: // CreateAclsRequest
		return apiVersion >= 2
	case 31: // DeleteAclsRequest
		return apiVersion >= 2
	case 32: // DescribeConfigsRequest
		return apiVersion >= 4
	case 33: // AlterConfigsRequest
		return apiVersion >= 2
	case 34: // AlterReplicaLogDirsRequest
		return apiVersion >= 2
	case 35: // DescribeLogDirsRequest
		return apiVersion >= 2
	case 36: // SaslAuthenticateRequest
		return apiVersion >= 2
	case 37: // CreatePartitionsRequest
		return apiVersion >= 2
	case 38: // CreateDelegationTokenRequest
		return apiVersion >= 2
	case 39: // RenewDelegationTokenRequest
		return apiVersion >= 2
	case 40: // ExpireDelegationTokenRequest
		return apiVersion >= 2
	case 41: // DescribeDelegationTokenRequest
		return apiVersion >= 2
	case 42: // DeleteGroupsRequest
		return apiVersion >= 2
	case 43: // ElectLeadersRequest
		return apiVersion >= 2
	case 44: // IncrementalAlterConfigsRequest
		return apiVersion >= 1
	case 45: // AlterPartitionReassignmentsRequest
		return true
	case 46: // ListPartitionReassignmentsRequest
		return true
	case 47: // OffsetDeleteRequest
		return false
	case 48: // DescribeClientQuotasRequest
		return apiVersion >= 1
	case 49: // AlterClientQuotasRequest
		return apiVersion >= 1
	case 50: // DescribeUserScramCredentialsRequest
		return true
	case 51: // AlterUserScramCredentialsRequest
		return true
	case 52: // VoteRequest
		return true
	case 53: // BeginQuorumEpochRequest
		return apiVersion >= 1
	case 54: // EndQuorumEpochRequest
		return apiVersion >= 1
	case 55: // DescribeQuorumRequest
		return true
	case 56: // AlterPartitionRequest
		return true
	case 57: // UpdateFeaturesRequest
		return true
	case 58: // EnvelopeRequest
		return true
	case 59: // FetchSnapshotRequest
		return true
	case 60: // DescribeClusterRequest
		return true
	case 61: // DescribeProducersRequest
		return true
	case 62: // BrokerRegistrationRequest
		return true
	case 63: // BrokerHeartbeatRequest
		return true
	case 64: // UnregisterBrokerRequest
		return true
	case 65: // DescribeTransactionsRequest
		return true
	case 66: // ListTransactionsRequest
		return true
	case 67: // AllocateProducerIdsRequest
		return true
	case 68: // ConsumerGroupHeartbeatRequest
		return true
	case 69: // ConsumerGroupDescribeRequest
		return true
	case 70: // ControllerRegistrationRequest
		return true
	case 71: // GetTelemetrySubscriptionsRequest
		return true
	case 72: // PushTelemetryRequest
		return true
	case 73: // AssignReplicasToDirsRequest
		return true
	case 74: // ListConfigResourcesRequest
		return true
	case 75: // DescribeTopicPartitionsRequest
		return true
	case 76: // ShareGroupHeartbeatRequest
		return true
	case 77: // ShareGroupDescribeRequest
		return true
	case 78: // ShareFetchRequest
		return true
	case 79: // ShareAcknowledgeRequest
		return true
	case 80: // AddRaftVoterRequest
		return true
	case 81: // RemoveRaftVoterRequest
		return true
	case 82: // UpdateRaftVoterRequest
		return true
	case 83: // InitializeShareGroupStateRequest
		return true
	case 84: // ReadShareGroupStateRequest
		return true
	case 85: // WriteShareGroupStateRequest
		return true
	case 86: // DeleteShareGroupStateRequest
		return true
	case 87: // ReadShareGroupStateSummaryRequest
		return true
	case 88: // StreamsGroupHeartbeatRequest
		return true
	case 89: // StreamsGroupDescribeRequest
		return true
	case 90: // DescribeShareGroupOffsetsRequest
		return true
	case 91: // AlterShareGroupOffsetsRequest
		return true
	case 92: // DeleteShareGroupOffsetsRequest
		return true
	}
	return false
}

// ReadResponseHeader decodes a Kafka response header. The wire form is just
// the correlation id (plus a tagged-fields count for flexible apiVersions),
// so the caller supplies a lookup that maps the just-read corrID back to the
// (apiKey, apiVersion) of the original request — typically by consulting an
// in-flight table — which is what we need to decide whether the header is
// flexible. A non-nil error from lookup is returned as-is.
func ReadResponseHeader(r *Reader, lookup func(corrID int32) (apiKey, apiVersion int16, err error)) (corrID int32, apiKey int16, apiVersion int16, err error) {
	corrID, err = r.ReadInt32()
	if err != nil {
		return
	}
	apiKey, apiVersion, err = lookup(corrID)
	if err != nil {
		return
	}
	if responseHeaderFlexible(apiKey, apiVersion) {
		if err = r.ReadTaggedFields(nil); err != nil {
			return
		}
	}
	return
}

// WriteResponseHeader encodes a Kafka response header (correlation id, plus
// an empty tagged-fields block for flexible apiVersions). apiKey and
// apiVersion are only used to decide whether the header is flexible.
func WriteResponseHeader(w *Writer, corrID int32, apiKey int16, apiVersion int16) {
	w.WriteInt32(corrID)
	if responseHeaderFlexible(apiKey, apiVersion) {
		w.WriteTaggedFields(nil)
	}
}

func responseHeaderFlexible(apiKey, apiVersion int16) bool {
	_ = apiVersion
	switch apiKey {
	case 0: // ProduceResponse
		return apiVersion >= 9
	case 1: // FetchResponse
		return apiVersion >= 12
	case 2: // ListOffsetsResponse
		return apiVersion >= 6
	case 3: // MetadataResponse
		return apiVersion >= 9
	case 8: // OffsetCommitResponse
		return apiVersion >= 8
	case 9: // OffsetFetchResponse
		return apiVersion >= 6
	case 10: // FindCoordinatorResponse
		return apiVersion >= 3
	case 11: // JoinGroupResponse
		return apiVersion >= 6
	case 12: // HeartbeatResponse
		return apiVersion >= 4
	case 13: // LeaveGroupResponse
		return apiVersion >= 4
	case 14: // SyncGroupResponse
		return apiVersion >= 4
	case 15: // DescribeGroupsResponse
		return apiVersion >= 5
	case 16: // ListGroupsResponse
		return apiVersion >= 3
	case 17: // SaslHandshakeResponse
		return false
	case 18: // ApiVersionsResponse — KIP-511: response header pinned to v0
		return false
	case 19: // CreateTopicsResponse
		return apiVersion >= 5
	case 20: // DeleteTopicsResponse
		return apiVersion >= 4
	case 21: // DeleteRecordsResponse
		return apiVersion >= 2
	case 22: // InitProducerIdResponse
		return apiVersion >= 2
	case 23: // OffsetForLeaderEpochResponse
		return apiVersion >= 4
	case 24: // AddPartitionsToTxnResponse
		return apiVersion >= 3
	case 25: // AddOffsetsToTxnResponse
		return apiVersion >= 3
	case 26: // EndTxnResponse
		return apiVersion >= 3
	case 27: // WriteTxnMarkersResponse
		return apiVersion >= 1
	case 28: // TxnOffsetCommitResponse
		return apiVersion >= 3
	case 29: // DescribeAclsResponse
		return apiVersion >= 2
	case 30: // CreateAclsResponse
		return apiVersion >= 2
	case 31: // DeleteAclsResponse
		return apiVersion >= 2
	case 32: // DescribeConfigsResponse
		return apiVersion >= 4
	case 33: // AlterConfigsResponse
		return apiVersion >= 2
	case 34: // AlterReplicaLogDirsResponse
		return apiVersion >= 2
	case 35: // DescribeLogDirsResponse
		return apiVersion >= 2
	case 36: // SaslAuthenticateResponse
		return apiVersion >= 2
	case 37: // CreatePartitionsResponse
		return apiVersion >= 2
	case 38: // CreateDelegationTokenResponse
		return apiVersion >= 2
	case 39: // RenewDelegationTokenResponse
		return apiVersion >= 2
	case 40: // ExpireDelegationTokenResponse
		return apiVersion >= 2
	case 41: // DescribeDelegationTokenResponse
		return apiVersion >= 2
	case 42: // DeleteGroupsResponse
		return apiVersion >= 2
	case 43: // ElectLeadersResponse
		return apiVersion >= 2
	case 44: // IncrementalAlterConfigsResponse
		return apiVersion >= 1
	case 45: // AlterPartitionReassignmentsResponse
		return true
	case 46: // ListPartitionReassignmentsResponse
		return true
	case 47: // OffsetDeleteResponse
		return false
	case 48: // DescribeClientQuotasResponse
		return apiVersion >= 1
	case 49: // AlterClientQuotasResponse
		return apiVersion >= 1
	case 50: // DescribeUserScramCredentialsResponse
		return true
	case 51: // AlterUserScramCredentialsResponse
		return true
	case 52: // VoteResponse
		return true
	case 53: // BeginQuorumEpochResponse
		return apiVersion >= 1
	case 54: // EndQuorumEpochResponse
		return apiVersion >= 1
	case 55: // DescribeQuorumResponse
		return true
	case 56: // AlterPartitionResponse
		return true
	case 57: // UpdateFeaturesResponse
		return true
	case 58: // EnvelopeResponse
		return true
	case 59: // FetchSnapshotResponse
		return true
	case 60: // DescribeClusterResponse
		return true
	case 61: // DescribeProducersResponse
		return true
	case 62: // BrokerRegistrationResponse
		return true
	case 63: // BrokerHeartbeatResponse
		return true
	case 64: // UnregisterBrokerResponse
		return true
	case 65: // DescribeTransactionsResponse
		return true
	case 66: // ListTransactionsResponse
		return true
	case 67: // AllocateProducerIdsResponse
		return true
	case 68: // ConsumerGroupHeartbeatResponse
		return true
	case 69: // ConsumerGroupDescribeResponse
		return true
	case 70: // ControllerRegistrationResponse
		return true
	case 71: // GetTelemetrySubscriptionsResponse
		return true
	case 72: // PushTelemetryResponse
		return true
	case 73: // AssignReplicasToDirsResponse
		return true
	case 74: // ListConfigResourcesResponse
		return true
	case 75: // DescribeTopicPartitionsResponse
		return true
	case 76: // ShareGroupHeartbeatResponse
		return true
	case 77: // ShareGroupDescribeResponse
		return true
	case 78: // ShareFetchResponse
		return true
	case 79: // ShareAcknowledgeResponse
		return true
	case 80: // AddRaftVoterResponse
		return true
	case 81: // RemoveRaftVoterResponse
		return true
	case 82: // UpdateRaftVoterResponse
		return true
	case 83: // InitializeShareGroupStateResponse
		return true
	case 84: // ReadShareGroupStateResponse
		return true
	case 85: // WriteShareGroupStateResponse
		return true
	case 86: // DeleteShareGroupStateResponse
		return true
	case 87: // ReadShareGroupStateSummaryResponse
		return true
	case 88: // StreamsGroupHeartbeatResponse
		return true
	case 89: // StreamsGroupDescribeResponse
		return true
	case 90: // DescribeShareGroupOffsetsResponse
		return true
	case 91: // AlterShareGroupOffsetsResponse
		return true
	case 92: // DeleteShareGroupOffsetsResponse
		return true
	}
	return false
}
