// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type EndQuorumEpochResponse struct {
	ErrorCode     int16
	Topics        []EndQuorumEpochResponseTopicData
	NodeEndpoints []EndQuorumEpochResponseNodeEndpoint
}

type EndQuorumEpochResponseNodeEndpoint struct {
	NodeId int32
	Host   string
	Port   uint16
}

type EndQuorumEpochResponsePartitionData struct {
	PartitionIndex int32
	ErrorCode      int16
	LeaderId       int32
	LeaderEpoch    int32
}

type EndQuorumEpochResponseTopicData struct {
	TopicName  string
	Partitions []EndQuorumEpochResponsePartitionData
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *EndQuorumEpochResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("EndQuorumEpochResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("EndQuorumEpochResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *EndQuorumEpochResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("EndQuorumEpochResponse v%d: %w", version, err)
	}
	return nil
}

func (m *EndQuorumEpochResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]EndQuorumEpochResponseTopicData, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(func(tag uint64, sub *Reader) error {
			switch tag {
			case 0:
				if !(version >= 1) {
					return nil
				}
				{
					var n int
					var err error
					if true {
						n, err = sub.ReadCompactArrayLen()
					} else {
						n, err = sub.ReadArrayLen()
					}
					if err != nil {
						return err
					}
					if n >= 0 {
						m.NodeEndpoints = make([]EndQuorumEpochResponseNodeEndpoint, n)
						for i := 0; i < n; i++ {
							if err := m.NodeEndpoints[i].decode(sub, version); err != nil {
								return err
							}
						}
					}
				}
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func (m *EndQuorumEpochResponseNodeEndpoint) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.NodeId = v
		}
	}
	if version >= 1 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Host = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Host = v
		}
	}
	if version >= 1 {
		{
			v, err := r.ReadUint16()
			if err != nil {
				return err
			}
			m.Port = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *EndQuorumEpochResponsePartitionData) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderEpoch = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *EndQuorumEpochResponseTopicData) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.TopicName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.TopicName = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]EndQuorumEpochResponsePartitionData, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *EndQuorumEpochResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		var tfs []TaggedField
		if version >= 1 {
			sub := NewWriter()
			{
				n := len(m.NodeEndpoints)
				if true {
					sub.WriteCompactArrayLen(n)
				} else {
					sub.WriteArrayLen(n)
				}
				for i := 0; i < n; i++ {
					if err := m.NodeEndpoints[i].encode(sub, version); err != nil {
						return err
					}
				}
			}
			tfs = append(tfs, TaggedField{Tag: 0, Body: sub.Bytes()})
		}
		w.WriteTaggedFields(tfs)
	}
	return nil
}

func (m *EndQuorumEpochResponseNodeEndpoint) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if version >= 1 {
		w.WriteInt32(m.NodeId)
	}
	if version >= 1 {
		if flexible {
			w.WriteCompactString(m.Host)
		} else {
			w.WriteString(m.Host)
		}
	}
	if version >= 1 {
		w.WriteUint16(m.Port)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *EndQuorumEpochResponsePartitionData) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt16(m.ErrorCode)
	w.WriteInt32(m.LeaderId)
	w.WriteInt32(m.LeaderEpoch)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *EndQuorumEpochResponseTopicData) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		w.WriteCompactString(m.TopicName)
	} else {
		w.WriteString(m.TopicName)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
