// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type EnvelopeRequest struct {
	RequestData       []byte
	RequestPrincipal  []byte
	ClientHostAddress []byte
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *EnvelopeRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("EnvelopeRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("EnvelopeRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *EnvelopeRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("EnvelopeRequest v%d: %w", version, err)
	}
	return nil
}

func (m *EnvelopeRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.RequestData = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.RequestData = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.RequestPrincipal = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.RequestPrincipal = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.ClientHostAddress = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.ClientHostAddress = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *EnvelopeRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactBytes(m.RequestData)
	} else {
		w.WriteBytes(m.RequestData)
	}
	if flexible {
		w.WriteCompactBytes(m.RequestPrincipal)
	} else {
		w.WriteBytes(m.RequestPrincipal)
	}
	if flexible {
		w.WriteCompactBytes(m.ClientHostAddress)
	} else {
		w.WriteBytes(m.ClientHostAddress)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
