// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type FetchSnapshotResponse struct {
	ThrottleTimeMs int32
	ErrorCode      int16
	Topics         []FetchSnapshotResponseTopicSnapshot
	NodeEndpoints  []FetchSnapshotResponseNodeEndpoint
}

type FetchSnapshotResponseLeaderIdAndEpoch struct {
	LeaderId    int32
	LeaderEpoch int32
}

type FetchSnapshotResponseNodeEndpoint struct {
	NodeId int32
	Host   string
	Port   uint16
}

type FetchSnapshotResponsePartitionSnapshot struct {
	Index            int32
	ErrorCode        int16
	SnapshotId       FetchSnapshotResponseSnapshotId
	CurrentLeader    FetchSnapshotResponseLeaderIdAndEpoch
	Size             int64
	Position         int64
	UnalignedRecords []byte
}

type FetchSnapshotResponseSnapshotId struct {
	EndOffset int64
	Epoch     int32
}

type FetchSnapshotResponseTopicSnapshot struct {
	Name       string
	Partitions []FetchSnapshotResponsePartitionSnapshot
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *FetchSnapshotResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("FetchSnapshotResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("FetchSnapshotResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *FetchSnapshotResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("FetchSnapshotResponse v%d: %w", version, err)
	}
	return nil
}

func (m *FetchSnapshotResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]FetchSnapshotResponseTopicSnapshot, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(func(tag uint64, sub *Reader) error {
			switch tag {
			case 0:
				if !(version >= 1) {
					return nil
				}
				{
					var n int
					var err error
					if true {
						n, err = sub.ReadCompactArrayLen()
					} else {
						n, err = sub.ReadArrayLen()
					}
					if err != nil {
						return err
					}
					if n >= 0 {
						m.NodeEndpoints = make([]FetchSnapshotResponseNodeEndpoint, n)
						for i := 0; i < n; i++ {
							if err := m.NodeEndpoints[i].decode(sub, version); err != nil {
								return err
							}
						}
					}
				}
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func (m *FetchSnapshotResponseLeaderIdAndEpoch) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderEpoch = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *FetchSnapshotResponseNodeEndpoint) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.NodeId = v
		}
	}
	if version >= 1 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Host = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Host = v
		}
	}
	if version >= 1 {
		{
			v, err := r.ReadUint16()
			if err != nil {
				return err
			}
			m.Port = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *FetchSnapshotResponsePartitionSnapshot) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Index = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if err := m.SnapshotId.decode(r, version); err != nil {
		return err
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.Size = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.Position = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.UnalignedRecords = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.UnalignedRecords = v
	}
	if flexible {
		if err := r.ReadTaggedFields(func(tag uint64, sub *Reader) error {
			switch tag {
			case 0:
				if !(true) {
					return nil
				}
				if err := m.CurrentLeader.decode(sub, version); err != nil {
					return err
				}
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func (m *FetchSnapshotResponseSnapshotId) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.EndOffset = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Epoch = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *FetchSnapshotResponseTopicSnapshot) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]FetchSnapshotResponsePartitionSnapshot, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *FetchSnapshotResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	w.WriteInt16(m.ErrorCode)
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		var tfs []TaggedField
		if version >= 1 {
			sub := NewWriter()
			{
				n := len(m.NodeEndpoints)
				if true {
					sub.WriteCompactArrayLen(n)
				} else {
					sub.WriteArrayLen(n)
				}
				for i := 0; i < n; i++ {
					if err := m.NodeEndpoints[i].encode(sub, version); err != nil {
						return err
					}
				}
			}
			tfs = append(tfs, TaggedField{Tag: 0, Body: sub.Bytes()})
		}
		w.WriteTaggedFields(tfs)
	}
	return nil
}

func (m *FetchSnapshotResponseLeaderIdAndEpoch) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.LeaderId)
	w.WriteInt32(m.LeaderEpoch)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *FetchSnapshotResponseNodeEndpoint) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if version >= 1 {
		w.WriteInt32(m.NodeId)
	}
	if version >= 1 {
		if flexible {
			w.WriteCompactString(m.Host)
		} else {
			w.WriteString(m.Host)
		}
	}
	if version >= 1 {
		w.WriteUint16(m.Port)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *FetchSnapshotResponsePartitionSnapshot) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.Index)
	w.WriteInt16(m.ErrorCode)
	if err := m.SnapshotId.encode(w, version); err != nil {
		return err
	}
	w.WriteInt64(m.Size)
	w.WriteInt64(m.Position)
	if flexible {
		w.WriteCompactBytes(m.UnalignedRecords)
	} else {
		w.WriteBytes(m.UnalignedRecords)
	}
	if flexible {
		var tfs []TaggedField
		if true {
			sub := NewWriter()
			if err := m.CurrentLeader.encode(sub, version); err != nil {
				return err
			}
			tfs = append(tfs, TaggedField{Tag: 0, Body: sub.Bytes()})
		}
		w.WriteTaggedFields(tfs)
	}
	return nil
}

func (m *FetchSnapshotResponseSnapshotId) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt64(m.EndOffset)
	w.WriteInt32(m.Epoch)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *FetchSnapshotResponseTopicSnapshot) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
