// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type FindCoordinatorResponse struct {
	ThrottleTimeMs int32
	ErrorCode      int16
	ErrorMessage   *string
	NodeId         int32
	Host           string
	Port           int32
	Coordinators   []FindCoordinatorResponseCoordinator
}

type FindCoordinatorResponseCoordinator struct {
	Key          string
	NodeId       int32
	Host         string
	Port         int32
	ErrorCode    int16
	ErrorMessage *string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *FindCoordinatorResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("FindCoordinatorResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("FindCoordinatorResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *FindCoordinatorResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("FindCoordinatorResponse v%d: %w", version, err)
	}
	return nil
}

func (m *FindCoordinatorResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.ThrottleTimeMs = v
		}
	}
	if version <= 3 {
		{
			v, err := r.ReadInt16()
			if err != nil {
				return err
			}
			m.ErrorCode = v
		}
	}
	if version >= 1 && version <= 3 {
		if version >= 1 && version <= 3 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.ErrorMessage = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.ErrorMessage = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.ErrorMessage = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.ErrorMessage = &s
			}
		}
	}
	if version <= 3 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.NodeId = v
		}
	}
	if version <= 3 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Host = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Host = v
		}
	}
	if version <= 3 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.Port = v
		}
	}
	if version >= 4 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.Coordinators = make([]FindCoordinatorResponseCoordinator, n)
				for i := 0; i < n; i++ {
					if err := m.Coordinators[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *FindCoordinatorResponseCoordinator) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 4 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Key = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Key = v
		}
	}
	if version >= 4 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.NodeId = v
		}
	}
	if version >= 4 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Host = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Host = v
		}
	}
	if version >= 4 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.Port = v
		}
	}
	if version >= 4 {
		{
			v, err := r.ReadInt16()
			if err != nil {
				return err
			}
			m.ErrorCode = v
		}
	}
	if version >= 4 {
		if version >= 4 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.ErrorMessage = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.ErrorMessage = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.ErrorMessage = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.ErrorMessage = &s
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *FindCoordinatorResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 1 {
		w.WriteInt32(m.ThrottleTimeMs)
	}
	if version <= 3 {
		w.WriteInt16(m.ErrorCode)
	}
	if version >= 1 && version <= 3 {
		if version >= 1 && version <= 3 {
			if flexible {
				w.WriteCompactNullableString(m.ErrorMessage)
			} else {
				w.WriteNullableString(m.ErrorMessage)
			}
		} else {
			if m.ErrorMessage == nil {
				return fmt.Errorf("ErrorMessage: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.ErrorMessage)
			} else {
				w.WriteString(*m.ErrorMessage)
			}
		}
	}
	if version <= 3 {
		w.WriteInt32(m.NodeId)
	}
	if version <= 3 {
		if flexible {
			w.WriteCompactString(m.Host)
		} else {
			w.WriteString(m.Host)
		}
	}
	if version <= 3 {
		w.WriteInt32(m.Port)
	}
	if version >= 4 {
		{
			n := len(m.Coordinators)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.Coordinators[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *FindCoordinatorResponseCoordinator) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 4 {
		if flexible {
			w.WriteCompactString(m.Key)
		} else {
			w.WriteString(m.Key)
		}
	}
	if version >= 4 {
		w.WriteInt32(m.NodeId)
	}
	if version >= 4 {
		if flexible {
			w.WriteCompactString(m.Host)
		} else {
			w.WriteString(m.Host)
		}
	}
	if version >= 4 {
		w.WriteInt32(m.Port)
	}
	if version >= 4 {
		w.WriteInt16(m.ErrorCode)
	}
	if version >= 4 {
		if version >= 4 {
			if flexible {
				w.WriteCompactNullableString(m.ErrorMessage)
			} else {
				w.WriteNullableString(m.ErrorMessage)
			}
		} else {
			if m.ErrorMessage == nil {
				return fmt.Errorf("ErrorMessage: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.ErrorMessage)
			} else {
				w.WriteString(*m.ErrorMessage)
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
