// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type GetTelemetrySubscriptionsResponse struct {
	ThrottleTimeMs           int32
	ErrorCode                int16
	ClientInstanceId         [16]byte
	SubscriptionId           int32
	AcceptedCompressionTypes []int8
	PushIntervalMs           int32
	TelemetryMaxBytes        int32
	DeltaTemporality         bool
	RequestedMetrics         []string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *GetTelemetrySubscriptionsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("GetTelemetrySubscriptionsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("GetTelemetrySubscriptionsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *GetTelemetrySubscriptionsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("GetTelemetrySubscriptionsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *GetTelemetrySubscriptionsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	{
		v, err := r.ReadUUID()
		if err != nil {
			return err
		}
		m.ClientInstanceId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.SubscriptionId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.AcceptedCompressionTypes = make([]int8, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt8()
					if err != nil {
						return err
					}
					m.AcceptedCompressionTypes[i] = v
				}
			}
		}
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PushIntervalMs = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.TelemetryMaxBytes = v
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.DeltaTemporality = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.RequestedMetrics = make([]string, n)
			for i := 0; i < n; i++ {
				if flexible {
					v, err := r.ReadCompactString()
					if err != nil {
						return err
					}
					m.RequestedMetrics[i] = v
				} else {
					v, err := r.ReadString()
					if err != nil {
						return err
					}
					m.RequestedMetrics[i] = v
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *GetTelemetrySubscriptionsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	w.WriteInt16(m.ErrorCode)
	w.WriteUUID(m.ClientInstanceId)
	w.WriteInt32(m.SubscriptionId)
	{
		n := len(m.AcceptedCompressionTypes)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt8(m.AcceptedCompressionTypes[i])
		}
	}
	w.WriteInt32(m.PushIntervalMs)
	w.WriteInt32(m.TelemetryMaxBytes)
	w.WriteBool(m.DeltaTemporality)
	{
		n := len(m.RequestedMetrics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if flexible {
				w.WriteCompactString(m.RequestedMetrics[i])
			} else {
				w.WriteString(m.RequestedMetrics[i])
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
