// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type IncrementalAlterConfigsRequest struct {
	Resources    []IncrementalAlterConfigsRequestAlterConfigsResource
	ValidateOnly bool
}

type IncrementalAlterConfigsRequestAlterConfigsResource struct {
	ResourceType int8
	ResourceName string
	Configs      []IncrementalAlterConfigsRequestAlterableConfig
}

type IncrementalAlterConfigsRequestAlterableConfig struct {
	Name            string
	ConfigOperation int8
	Value           *string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *IncrementalAlterConfigsRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("IncrementalAlterConfigsRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("IncrementalAlterConfigsRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *IncrementalAlterConfigsRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("IncrementalAlterConfigsRequest v%d: %w", version, err)
	}
	return nil
}

func (m *IncrementalAlterConfigsRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Resources = make([]IncrementalAlterConfigsRequestAlterConfigsResource, n)
			for i := 0; i < n; i++ {
				if err := m.Resources[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.ValidateOnly = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *IncrementalAlterConfigsRequestAlterConfigsResource) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.ResourceType = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ResourceName = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ResourceName = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Configs = make([]IncrementalAlterConfigsRequestAlterableConfig, n)
			for i := 0; i < n; i++ {
				if err := m.Configs[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *IncrementalAlterConfigsRequestAlterableConfig) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.ConfigOperation = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.Value = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.Value = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *IncrementalAlterConfigsRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		n := len(m.Resources)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Resources[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	w.WriteBool(m.ValidateOnly)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *IncrementalAlterConfigsRequestAlterConfigsResource) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	w.WriteInt8(m.ResourceType)
	if flexible {
		w.WriteCompactString(m.ResourceName)
	} else {
		w.WriteString(m.ResourceName)
	}
	{
		n := len(m.Configs)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Configs[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *IncrementalAlterConfigsRequestAlterableConfig) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	w.WriteInt8(m.ConfigOperation)
	if flexible {
		w.WriteCompactNullableString(m.Value)
	} else {
		w.WriteNullableString(m.Value)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
