// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type InitProducerIdRequest struct {
	TransactionalId      *string
	TransactionTimeoutMs int32
	ProducerId           int64
	ProducerEpoch        int16
	Enable2Pc            bool
	KeepPreparedTxn      bool
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *InitProducerIdRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("InitProducerIdRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("InitProducerIdRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *InitProducerIdRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("InitProducerIdRequest v%d: %w", version, err)
	}
	return nil
}

func (m *InitProducerIdRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.TransactionalId = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.TransactionalId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.TransactionTimeoutMs = v
	}
	if version >= 3 {
		{
			v, err := r.ReadInt64()
			if err != nil {
				return err
			}
			m.ProducerId = v
		}
	}
	if version >= 3 {
		{
			v, err := r.ReadInt16()
			if err != nil {
				return err
			}
			m.ProducerEpoch = v
		}
	}
	if version >= 6 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.Enable2Pc = v
		}
	}
	if version >= 6 {
		{
			v, err := r.ReadBool()
			if err != nil {
				return err
			}
			m.KeepPreparedTxn = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *InitProducerIdRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	if flexible {
		w.WriteCompactNullableString(m.TransactionalId)
	} else {
		w.WriteNullableString(m.TransactionalId)
	}
	w.WriteInt32(m.TransactionTimeoutMs)
	if version >= 3 {
		w.WriteInt64(m.ProducerId)
	}
	if version >= 3 {
		w.WriteInt16(m.ProducerEpoch)
	}
	if version >= 6 {
		w.WriteBool(m.Enable2Pc)
	}
	if version >= 6 {
		w.WriteBool(m.KeepPreparedTxn)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
