// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type JoinGroupRequest struct {
	GroupId            string
	SessionTimeoutMs   int32
	RebalanceTimeoutMs int32
	MemberId           string
	GroupInstanceId    *string
	ProtocolType       string
	Protocols          []JoinGroupRequestProtocol
	Reason             *string
}

type JoinGroupRequestProtocol struct {
	Name     string
	Metadata []byte
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *JoinGroupRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("JoinGroupRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("JoinGroupRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *JoinGroupRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("JoinGroupRequest v%d: %w", version, err)
	}
	return nil
}

func (m *JoinGroupRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.SessionTimeoutMs = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.RebalanceTimeoutMs = v
		}
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.MemberId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.MemberId = v
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.GroupInstanceId = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.GroupInstanceId = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.GroupInstanceId = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.GroupInstanceId = &s
			}
		}
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ProtocolType = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ProtocolType = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Protocols = make([]JoinGroupRequestProtocol, n)
			for i := 0; i < n; i++ {
				if err := m.Protocols[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if version >= 8 {
		if version >= 8 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.Reason = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.Reason = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.Reason = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.Reason = &s
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *JoinGroupRequestProtocol) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.Metadata = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.Metadata = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *JoinGroupRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	if flexible {
		w.WriteCompactString(m.GroupId)
	} else {
		w.WriteString(m.GroupId)
	}
	w.WriteInt32(m.SessionTimeoutMs)
	if version >= 1 {
		w.WriteInt32(m.RebalanceTimeoutMs)
	}
	if flexible {
		w.WriteCompactString(m.MemberId)
	} else {
		w.WriteString(m.MemberId)
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				w.WriteCompactNullableString(m.GroupInstanceId)
			} else {
				w.WriteNullableString(m.GroupInstanceId)
			}
		} else {
			if m.GroupInstanceId == nil {
				return fmt.Errorf("GroupInstanceId: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.GroupInstanceId)
			} else {
				w.WriteString(*m.GroupInstanceId)
			}
		}
	}
	if flexible {
		w.WriteCompactString(m.ProtocolType)
	} else {
		w.WriteString(m.ProtocolType)
	}
	{
		n := len(m.Protocols)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Protocols[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if version >= 8 {
		if version >= 8 {
			if flexible {
				w.WriteCompactNullableString(m.Reason)
			} else {
				w.WriteNullableString(m.Reason)
			}
		} else {
			if m.Reason == nil {
				return fmt.Errorf("Reason: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.Reason)
			} else {
				w.WriteString(*m.Reason)
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *JoinGroupRequestProtocol) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	if flexible {
		w.WriteCompactBytes(m.Metadata)
	} else {
		w.WriteBytes(m.Metadata)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
