// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type KRaftVersionRecord struct {
	Version      int16
	KRaftVersion int16
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *KRaftVersionRecord) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("KRaftVersionRecord v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("KRaftVersionRecord v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *KRaftVersionRecord) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("KRaftVersionRecord v%d: %w", version, err)
	}
	return nil
}

func (m *KRaftVersionRecord) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.Version = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.KRaftVersion = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *KRaftVersionRecord) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt16(m.Version)
	w.WriteInt16(m.KRaftVersion)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
