// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type LeaveGroupResponse struct {
	ThrottleTimeMs int32
	ErrorCode      int16
	Members        []LeaveGroupResponseMemberResponse
}

type LeaveGroupResponseMemberResponse struct {
	MemberId        string
	GroupInstanceId *string
	ErrorCode       int16
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *LeaveGroupResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("LeaveGroupResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("LeaveGroupResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *LeaveGroupResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("LeaveGroupResponse v%d: %w", version, err)
	}
	return nil
}

func (m *LeaveGroupResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.ThrottleTimeMs = v
		}
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if version >= 3 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.Members = make([]LeaveGroupResponseMemberResponse, n)
				for i := 0; i < n; i++ {
					if err := m.Members[i].decode(r, version); err != nil {
						return err
					}
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *LeaveGroupResponseMemberResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 3 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.MemberId = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.MemberId = v
		}
	}
	if version >= 3 {
		if version >= 3 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.GroupInstanceId = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.GroupInstanceId = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.GroupInstanceId = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.GroupInstanceId = &s
			}
		}
	}
	if version >= 3 {
		{
			v, err := r.ReadInt16()
			if err != nil {
				return err
			}
			m.ErrorCode = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *LeaveGroupResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 1 {
		w.WriteInt32(m.ThrottleTimeMs)
	}
	w.WriteInt16(m.ErrorCode)
	if version >= 3 {
		{
			n := len(m.Members)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.Members[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *LeaveGroupResponseMemberResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 3 {
		if flexible {
			w.WriteCompactString(m.MemberId)
		} else {
			w.WriteString(m.MemberId)
		}
	}
	if version >= 3 {
		if version >= 3 {
			if flexible {
				w.WriteCompactNullableString(m.GroupInstanceId)
			} else {
				w.WriteNullableString(m.GroupInstanceId)
			}
		} else {
			if m.GroupInstanceId == nil {
				return fmt.Errorf("GroupInstanceId: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.GroupInstanceId)
			} else {
				w.WriteString(*m.GroupInstanceId)
			}
		}
	}
	if version >= 3 {
		w.WriteInt16(m.ErrorCode)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
