// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ListOffsetsRequest struct {
	ReplicaId      int32
	IsolationLevel int8
	Topics         []ListOffsetsRequestListOffsetsTopic
	TimeoutMs      int32
}

type ListOffsetsRequestListOffsetsPartition struct {
	PartitionIndex     int32
	CurrentLeaderEpoch int32
	Timestamp          int64
}

type ListOffsetsRequestListOffsetsTopic struct {
	Name       string
	Partitions []ListOffsetsRequestListOffsetsPartition
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ListOffsetsRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ListOffsetsRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ListOffsetsRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ListOffsetsRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ListOffsetsRequest v%d: %w", version, err)
	}
	return nil
}

func (m *ListOffsetsRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ReplicaId = v
	}
	if version >= 2 {
		{
			v, err := r.ReadInt8()
			if err != nil {
				return err
			}
			m.IsolationLevel = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]ListOffsetsRequestListOffsetsTopic, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if version >= 10 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.TimeoutMs = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ListOffsetsRequestListOffsetsPartition) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	if version >= 4 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.CurrentLeaderEpoch = v
		}
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.Timestamp = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ListOffsetsRequestListOffsetsTopic) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]ListOffsetsRequestListOffsetsPartition, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ListOffsetsRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	w.WriteInt32(m.ReplicaId)
	if version >= 2 {
		w.WriteInt8(m.IsolationLevel)
	}
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if version >= 10 {
		w.WriteInt32(m.TimeoutMs)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ListOffsetsRequestListOffsetsPartition) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	if version >= 4 {
		w.WriteInt32(m.CurrentLeaderEpoch)
	}
	w.WriteInt64(m.Timestamp)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ListOffsetsRequestListOffsetsTopic) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 6
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
