// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ListTransactionsRequest struct {
	StateFilters           []string
	ProducerIdFilters      []int64
	DurationFilter         int64
	TransactionalIdPattern *string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ListTransactionsRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ListTransactionsRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ListTransactionsRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ListTransactionsRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ListTransactionsRequest v%d: %w", version, err)
	}
	return nil
}

func (m *ListTransactionsRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.StateFilters = make([]string, n)
			for i := 0; i < n; i++ {
				if flexible {
					v, err := r.ReadCompactString()
					if err != nil {
						return err
					}
					m.StateFilters[i] = v
				} else {
					v, err := r.ReadString()
					if err != nil {
						return err
					}
					m.StateFilters[i] = v
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.ProducerIdFilters = make([]int64, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt64()
					if err != nil {
						return err
					}
					m.ProducerIdFilters[i] = v
				}
			}
		}
	}
	if version >= 1 {
		{
			v, err := r.ReadInt64()
			if err != nil {
				return err
			}
			m.DurationFilter = v
		}
	}
	if version >= 2 {
		if version >= 2 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.TransactionalIdPattern = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.TransactionalIdPattern = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.TransactionalIdPattern = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.TransactionalIdPattern = &s
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ListTransactionsRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		n := len(m.StateFilters)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if flexible {
				w.WriteCompactString(m.StateFilters[i])
			} else {
				w.WriteString(m.StateFilters[i])
			}
		}
	}
	{
		n := len(m.ProducerIdFilters)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt64(m.ProducerIdFilters[i])
		}
	}
	if version >= 1 {
		w.WriteInt64(m.DurationFilter)
	}
	if version >= 2 {
		if version >= 2 {
			if flexible {
				w.WriteCompactNullableString(m.TransactionalIdPattern)
			} else {
				w.WriteNullableString(m.TransactionalIdPattern)
			}
		} else {
			if m.TransactionalIdPattern == nil {
				return fmt.Errorf("TransactionalIdPattern: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.TransactionalIdPattern)
			} else {
				w.WriteString(*m.TransactionalIdPattern)
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
