// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ListGroupsResponse struct {
	ThrottleTimeMs int32
	ErrorCode      int16
	Groups         []ListGroupsResponseListedGroup
}

type ListGroupsResponseListedGroup struct {
	GroupId      string
	ProtocolType string
	GroupState   string
	GroupType    string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ListGroupsResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ListGroupsResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ListGroupsResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ListGroupsResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ListGroupsResponse v%d: %w", version, err)
	}
	return nil
}

func (m *ListGroupsResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.ThrottleTimeMs = v
		}
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Groups = make([]ListGroupsResponseListedGroup, n)
			for i := 0; i < n; i++ {
				if err := m.Groups[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ListGroupsResponseListedGroup) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupId = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ProtocolType = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ProtocolType = v
	}
	if version >= 4 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.GroupState = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.GroupState = v
		}
	}
	if version >= 5 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.GroupType = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.GroupType = v
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ListGroupsResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 1 {
		w.WriteInt32(m.ThrottleTimeMs)
	}
	w.WriteInt16(m.ErrorCode)
	{
		n := len(m.Groups)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Groups[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ListGroupsResponseListedGroup) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if flexible {
		w.WriteCompactString(m.GroupId)
	} else {
		w.WriteString(m.GroupId)
	}
	if flexible {
		w.WriteCompactString(m.ProtocolType)
	} else {
		w.WriteString(m.ProtocolType)
	}
	if version >= 4 {
		if flexible {
			w.WriteCompactString(m.GroupState)
		} else {
			w.WriteString(m.GroupState)
		}
	}
	if version >= 5 {
		if flexible {
			w.WriteCompactString(m.GroupType)
		} else {
			w.WriteString(m.GroupType)
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
