// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ListGroupsRequest struct {
	StatesFilter []string
	TypesFilter  []string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ListGroupsRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ListGroupsRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ListGroupsRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ListGroupsRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ListGroupsRequest v%d: %w", version, err)
	}
	return nil
}

func (m *ListGroupsRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 4 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.StatesFilter = make([]string, n)
				for i := 0; i < n; i++ {
					if flexible {
						v, err := r.ReadCompactString()
						if err != nil {
							return err
						}
						m.StatesFilter[i] = v
					} else {
						v, err := r.ReadString()
						if err != nil {
							return err
						}
						m.StatesFilter[i] = v
					}
				}
			}
		}
	}
	if version >= 5 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.TypesFilter = make([]string, n)
				for i := 0; i < n; i++ {
					if flexible {
						v, err := r.ReadCompactString()
						if err != nil {
							return err
						}
						m.TypesFilter[i] = v
					} else {
						v, err := r.ReadString()
						if err != nil {
							return err
						}
						m.TypesFilter[i] = v
					}
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ListGroupsRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 3
	_ = flexible
	if version >= 4 {
		{
			n := len(m.StatesFilter)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if flexible {
					w.WriteCompactString(m.StatesFilter[i])
				} else {
					w.WriteString(m.StatesFilter[i])
				}
			}
		}
	}
	if version >= 5 {
		{
			n := len(m.TypesFilter)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if flexible {
					w.WriteCompactString(m.TypesFilter[i])
				} else {
					w.WriteString(m.TypesFilter[i])
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
