// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ListConfigResourcesRequest struct {
	ResourceTypes []int8
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ListConfigResourcesRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ListConfigResourcesRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ListConfigResourcesRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ListConfigResourcesRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ListConfigResourcesRequest v%d: %w", version, err)
	}
	return nil
}

func (m *ListConfigResourcesRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if version >= 1 {
		{
			var n int
			var err error
			if flexible {
				n, err = r.ReadCompactArrayLen()
			} else {
				n, err = r.ReadArrayLen()
			}
			if err != nil {
				return err
			}
			if n >= 0 {
				m.ResourceTypes = make([]int8, n)
				for i := 0; i < n; i++ {
					{
						v, err := r.ReadInt8()
						if err != nil {
							return err
						}
						m.ResourceTypes[i] = v
					}
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ListConfigResourcesRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if version >= 1 {
		{
			n := len(m.ResourceTypes)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				w.WriteInt8(m.ResourceTypes[i])
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
