// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type OffsetCommitRequest struct {
	GroupId                   string
	GenerationIdOrMemberEpoch int32
	MemberId                  string
	GroupInstanceId           *string
	RetentionTimeMs           int64
	Topics                    []OffsetCommitRequestTopic
}

type OffsetCommitRequestPartition struct {
	PartitionIndex       int32
	CommittedOffset      int64
	CommittedLeaderEpoch int32
	CommittedMetadata    *string
}

type OffsetCommitRequestTopic struct {
	Name       string
	TopicId    [16]byte
	Partitions []OffsetCommitRequestPartition
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *OffsetCommitRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("OffsetCommitRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("OffsetCommitRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *OffsetCommitRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("OffsetCommitRequest v%d: %w", version, err)
	}
	return nil
}

func (m *OffsetCommitRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 8
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupId = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.GenerationIdOrMemberEpoch = v
		}
	}
	if version >= 1 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.MemberId = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.MemberId = v
		}
	}
	if version >= 7 {
		if version >= 7 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.GroupInstanceId = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.GroupInstanceId = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.GroupInstanceId = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.GroupInstanceId = &s
			}
		}
	}
	if version >= 2 && version <= 4 {
		{
			v, err := r.ReadInt64()
			if err != nil {
				return err
			}
			m.RetentionTimeMs = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]OffsetCommitRequestTopic, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *OffsetCommitRequestPartition) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 8
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.CommittedOffset = v
	}
	if version >= 6 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.CommittedLeaderEpoch = v
		}
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.CommittedMetadata = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.CommittedMetadata = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *OffsetCommitRequestTopic) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 8
	_ = flexible
	if version <= 9 {
		if flexible {
			v, err := r.ReadCompactString()
			if err != nil {
				return err
			}
			m.Name = v
		} else {
			v, err := r.ReadString()
			if err != nil {
				return err
			}
			m.Name = v
		}
	}
	if version >= 10 {
		{
			v, err := r.ReadUUID()
			if err != nil {
				return err
			}
			m.TopicId = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]OffsetCommitRequestPartition, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *OffsetCommitRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 8
	_ = flexible
	if flexible {
		w.WriteCompactString(m.GroupId)
	} else {
		w.WriteString(m.GroupId)
	}
	if version >= 1 {
		w.WriteInt32(m.GenerationIdOrMemberEpoch)
	}
	if version >= 1 {
		if flexible {
			w.WriteCompactString(m.MemberId)
		} else {
			w.WriteString(m.MemberId)
		}
	}
	if version >= 7 {
		if version >= 7 {
			if flexible {
				w.WriteCompactNullableString(m.GroupInstanceId)
			} else {
				w.WriteNullableString(m.GroupInstanceId)
			}
		} else {
			if m.GroupInstanceId == nil {
				return fmt.Errorf("GroupInstanceId: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.GroupInstanceId)
			} else {
				w.WriteString(*m.GroupInstanceId)
			}
		}
	}
	if version >= 2 && version <= 4 {
		w.WriteInt64(m.RetentionTimeMs)
	}
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *OffsetCommitRequestPartition) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 8
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt64(m.CommittedOffset)
	if version >= 6 {
		w.WriteInt32(m.CommittedLeaderEpoch)
	}
	if flexible {
		w.WriteCompactNullableString(m.CommittedMetadata)
	} else {
		w.WriteNullableString(m.CommittedMetadata)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *OffsetCommitRequestTopic) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 8
	_ = flexible
	if version <= 9 {
		if flexible {
			w.WriteCompactString(m.Name)
		} else {
			w.WriteString(m.Name)
		}
	}
	if version >= 10 {
		w.WriteUUID(m.TopicId)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
