// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type OffsetForLeaderEpochResponse struct {
	ThrottleTimeMs int32
	Topics         []OffsetForLeaderEpochResponseOffsetForLeaderTopicResult
}

type OffsetForLeaderEpochResponseEpochEndOffset struct {
	ErrorCode   int16
	Partition   int32
	LeaderEpoch int32
	EndOffset   int64
}

type OffsetForLeaderEpochResponseOffsetForLeaderTopicResult struct {
	Topic      string
	Partitions []OffsetForLeaderEpochResponseEpochEndOffset
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *OffsetForLeaderEpochResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("OffsetForLeaderEpochResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("OffsetForLeaderEpochResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *OffsetForLeaderEpochResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("OffsetForLeaderEpochResponse v%d: %w", version, err)
	}
	return nil
}

func (m *OffsetForLeaderEpochResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 2 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.ThrottleTimeMs = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]OffsetForLeaderEpochResponseOffsetForLeaderTopicResult, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *OffsetForLeaderEpochResponseEpochEndOffset) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Partition = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.LeaderEpoch = v
		}
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.EndOffset = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *OffsetForLeaderEpochResponseOffsetForLeaderTopicResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Topic = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Topic = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]OffsetForLeaderEpochResponseEpochEndOffset, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *OffsetForLeaderEpochResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 2 {
		w.WriteInt32(m.ThrottleTimeMs)
	}
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *OffsetForLeaderEpochResponseEpochEndOffset) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	w.WriteInt32(m.Partition)
	if version >= 1 {
		w.WriteInt32(m.LeaderEpoch)
	}
	w.WriteInt64(m.EndOffset)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *OffsetForLeaderEpochResponseOffsetForLeaderTopicResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Topic)
	} else {
		w.WriteString(m.Topic)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
