// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type PushTelemetryRequest struct {
	ClientInstanceId [16]byte
	SubscriptionId   int32
	Terminating      bool
	CompressionType  int8
	Metrics          []byte
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *PushTelemetryRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("PushTelemetryRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("PushTelemetryRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *PushTelemetryRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("PushTelemetryRequest v%d: %w", version, err)
	}
	return nil
}

func (m *PushTelemetryRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadUUID()
		if err != nil {
			return err
		}
		m.ClientInstanceId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.SubscriptionId = v
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.Terminating = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.CompressionType = v
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.Metrics = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.Metrics = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *PushTelemetryRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteUUID(m.ClientInstanceId)
	w.WriteInt32(m.SubscriptionId)
	w.WriteBool(m.Terminating)
	w.WriteInt8(m.CompressionType)
	if flexible {
		w.WriteCompactBytes(m.Metrics)
	} else {
		w.WriteBytes(m.Metrics)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
