// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ReadShareGroupStateResponse struct {
	Results []ReadShareGroupStateResponseReadStateResult
}

type ReadShareGroupStateResponsePartitionResult struct {
	Partition    int32
	ErrorCode    int16
	ErrorMessage *string
	StateEpoch   int32
	StartOffset  int64
	StateBatches []ReadShareGroupStateResponseStateBatch
}

type ReadShareGroupStateResponseReadStateResult struct {
	TopicId    [16]byte
	Partitions []ReadShareGroupStateResponsePartitionResult
}

type ReadShareGroupStateResponseStateBatch struct {
	FirstOffset   int64
	LastOffset    int64
	DeliveryState int8
	DeliveryCount int16
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ReadShareGroupStateResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ReadShareGroupStateResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ReadShareGroupStateResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ReadShareGroupStateResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ReadShareGroupStateResponse v%d: %w", version, err)
	}
	return nil
}

func (m *ReadShareGroupStateResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Results = make([]ReadShareGroupStateResponseReadStateResult, n)
			for i := 0; i < n; i++ {
				if err := m.Results[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ReadShareGroupStateResponsePartitionResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Partition = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.StateEpoch = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.StartOffset = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.StateBatches = make([]ReadShareGroupStateResponseStateBatch, n)
			for i := 0; i < n; i++ {
				if err := m.StateBatches[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ReadShareGroupStateResponseReadStateResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadUUID()
		if err != nil {
			return err
		}
		m.TopicId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]ReadShareGroupStateResponsePartitionResult, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ReadShareGroupStateResponseStateBatch) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.FirstOffset = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.LastOffset = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.DeliveryState = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.DeliveryCount = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ReadShareGroupStateResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		n := len(m.Results)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Results[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ReadShareGroupStateResponsePartitionResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.Partition)
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	w.WriteInt32(m.StateEpoch)
	w.WriteInt64(m.StartOffset)
	{
		n := len(m.StateBatches)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.StateBatches[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ReadShareGroupStateResponseReadStateResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteUUID(m.TopicId)
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ReadShareGroupStateResponseStateBatch) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt64(m.FirstOffset)
	w.WriteInt64(m.LastOffset)
	w.WriteInt8(m.DeliveryState)
	w.WriteInt16(m.DeliveryCount)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
