// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type RenewDelegationTokenResponse struct {
	ErrorCode         int16
	ExpiryTimestampMs int64
	ThrottleTimeMs    int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *RenewDelegationTokenResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("RenewDelegationTokenResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("RenewDelegationTokenResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *RenewDelegationTokenResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("RenewDelegationTokenResponse v%d: %w", version, err)
	}
	return nil
}

func (m *RenewDelegationTokenResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.ExpiryTimestampMs = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *RenewDelegationTokenResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	w.WriteInt64(m.ExpiryTimestampMs)
	w.WriteInt32(m.ThrottleTimeMs)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
