// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type RequestHeader struct {
	RequestApiKey     int16
	RequestApiVersion int16
	CorrelationId     int32
	ClientId          *string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *RequestHeader) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("RequestHeader v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("RequestHeader v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *RequestHeader) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("RequestHeader v%d: %w", version, err)
	}
	return nil
}

func (m *RequestHeader) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.RequestApiKey = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.RequestApiVersion = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.CorrelationId = v
	}
	if version >= 1 {
		if version >= 1 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.ClientId = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.ClientId = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.ClientId = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.ClientId = &s
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *RequestHeader) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 2
	_ = flexible
	w.WriteInt16(m.RequestApiKey)
	w.WriteInt16(m.RequestApiVersion)
	w.WriteInt32(m.CorrelationId)
	if version >= 1 {
		if version >= 1 {
			if flexible {
				w.WriteCompactNullableString(m.ClientId)
			} else {
				w.WriteNullableString(m.ClientId)
			}
		} else {
			if m.ClientId == nil {
				return fmt.Errorf("ClientId: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.ClientId)
			} else {
				w.WriteString(*m.ClientId)
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
