// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type SaslHandshakeRequest struct {
	Mechanism string
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *SaslHandshakeRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("SaslHandshakeRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("SaslHandshakeRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *SaslHandshakeRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("SaslHandshakeRequest v%d: %w", version, err)
	}
	return nil
}

func (m *SaslHandshakeRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := false
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Mechanism = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Mechanism = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *SaslHandshakeRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := false
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Mechanism)
	} else {
		w.WriteString(m.Mechanism)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
