// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type ShareFetchResponse struct {
	ThrottleTimeMs           int32
	ErrorCode                int16
	ErrorMessage             *string
	AcquisitionLockTimeoutMs int32
	Responses                []ShareFetchResponseShareFetchableTopicResponse
	NodeEndpoints            []ShareFetchResponseNodeEndpoint
}

type ShareFetchResponseAcquiredRecords struct {
	FirstOffset   int64
	LastOffset    int64
	DeliveryCount int16
}

type ShareFetchResponseLeaderIdAndEpoch struct {
	LeaderId    int32
	LeaderEpoch int32
}

type ShareFetchResponseNodeEndpoint struct {
	NodeId int32
	Host   string
	Port   int32
	Rack   *string
}

type ShareFetchResponsePartitionData struct {
	PartitionIndex          int32
	ErrorCode               int16
	ErrorMessage            *string
	AcknowledgeErrorCode    int16
	AcknowledgeErrorMessage *string
	CurrentLeader           ShareFetchResponseLeaderIdAndEpoch
	Records                 []byte
	AcquiredRecords         []ShareFetchResponseAcquiredRecords
}

type ShareFetchResponseShareFetchableTopicResponse struct {
	TopicId    [16]byte
	Partitions []ShareFetchResponsePartitionData
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *ShareFetchResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("ShareFetchResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("ShareFetchResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *ShareFetchResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("ShareFetchResponse v%d: %w", version, err)
	}
	return nil
}

func (m *ShareFetchResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.AcquisitionLockTimeoutMs = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Responses = make([]ShareFetchResponseShareFetchableTopicResponse, n)
			for i := 0; i < n; i++ {
				if err := m.Responses[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.NodeEndpoints = make([]ShareFetchResponseNodeEndpoint, n)
			for i := 0; i < n; i++ {
				if err := m.NodeEndpoints[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ShareFetchResponseAcquiredRecords) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.FirstOffset = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.LastOffset = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.DeliveryCount = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ShareFetchResponseLeaderIdAndEpoch) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderEpoch = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ShareFetchResponseNodeEndpoint) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.NodeId = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Host = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Host = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Port = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.Rack = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.Rack = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ShareFetchResponsePartitionData) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.AcknowledgeErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.AcknowledgeErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.AcknowledgeErrorMessage = v
	}
	if err := m.CurrentLeader.decode(r, version); err != nil {
		return err
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.Records = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.Records = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.AcquiredRecords = make([]ShareFetchResponseAcquiredRecords, n)
			for i := 0; i < n; i++ {
				if err := m.AcquiredRecords[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ShareFetchResponseShareFetchableTopicResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadUUID()
		if err != nil {
			return err
		}
		m.TopicId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]ShareFetchResponsePartitionData, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *ShareFetchResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	if version >= 1 {
		w.WriteInt32(m.AcquisitionLockTimeoutMs)
	}
	{
		n := len(m.Responses)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Responses[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.NodeEndpoints)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.NodeEndpoints[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ShareFetchResponseAcquiredRecords) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt64(m.FirstOffset)
	w.WriteInt64(m.LastOffset)
	w.WriteInt16(m.DeliveryCount)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ShareFetchResponseLeaderIdAndEpoch) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.LeaderId)
	w.WriteInt32(m.LeaderEpoch)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ShareFetchResponseNodeEndpoint) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.NodeId)
	if flexible {
		w.WriteCompactString(m.Host)
	} else {
		w.WriteString(m.Host)
	}
	w.WriteInt32(m.Port)
	if flexible {
		w.WriteCompactNullableString(m.Rack)
	} else {
		w.WriteNullableString(m.Rack)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ShareFetchResponsePartitionData) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	w.WriteInt16(m.AcknowledgeErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.AcknowledgeErrorMessage)
	} else {
		w.WriteNullableString(m.AcknowledgeErrorMessage)
	}
	if err := m.CurrentLeader.encode(w, version); err != nil {
		return err
	}
	if flexible {
		w.WriteCompactBytes(m.Records)
	} else {
		w.WriteBytes(m.Records)
	}
	{
		n := len(m.AcquiredRecords)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.AcquiredRecords[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *ShareFetchResponseShareFetchableTopicResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteUUID(m.TopicId)
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
