// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type StreamsGroupHeartbeatResponse struct {
	ThrottleTimeMs           int32
	ErrorCode                int16
	ErrorMessage             *string
	MemberId                 string
	MemberEpoch              int32
	HeartbeatIntervalMs      int32
	AcceptableRecoveryLag    int32
	TaskOffsetIntervalMs     int32
	Status                   []StreamsGroupHeartbeatResponseStatus
	ActiveTasks              []StreamsGroupHeartbeatResponseTaskIds
	StandbyTasks             []StreamsGroupHeartbeatResponseTaskIds
	WarmupTasks              []StreamsGroupHeartbeatResponseTaskIds
	EndpointInformationEpoch int32
	PartitionsByUserEndpoint []StreamsGroupHeartbeatResponseEndpointToPartitions
}

type StreamsGroupHeartbeatResponseEndpoint struct {
	Host string
	Port uint16
}

type StreamsGroupHeartbeatResponseEndpointToPartitions struct {
	UserEndpoint      StreamsGroupHeartbeatResponseEndpoint
	ActivePartitions  []StreamsGroupHeartbeatResponseTopicPartition
	StandbyPartitions []StreamsGroupHeartbeatResponseTopicPartition
}

type StreamsGroupHeartbeatResponseStatus struct {
	StatusCode   int8
	StatusDetail string
}

type StreamsGroupHeartbeatResponseTaskIds struct {
	SubtopologyId string
	Partitions    []int32
}

type StreamsGroupHeartbeatResponseTopicPartition struct {
	Topic      string
	Partitions []int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *StreamsGroupHeartbeatResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("StreamsGroupHeartbeatResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *StreamsGroupHeartbeatResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponse v%d: %w", version, err)
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.MemberId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.MemberId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.MemberEpoch = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.HeartbeatIntervalMs = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.AcceptableRecoveryLag = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.TaskOffsetIntervalMs = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Status = make([]StreamsGroupHeartbeatResponseStatus, n)
			for i := 0; i < n; i++ {
				if err := m.Status[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.ActiveTasks = make([]StreamsGroupHeartbeatResponseTaskIds, n)
			for i := 0; i < n; i++ {
				if err := m.ActiveTasks[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.StandbyTasks = make([]StreamsGroupHeartbeatResponseTaskIds, n)
			for i := 0; i < n; i++ {
				if err := m.StandbyTasks[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.WarmupTasks = make([]StreamsGroupHeartbeatResponseTaskIds, n)
			for i := 0; i < n; i++ {
				if err := m.WarmupTasks[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.EndpointInformationEpoch = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.PartitionsByUserEndpoint = make([]StreamsGroupHeartbeatResponseEndpointToPartitions, n)
			for i := 0; i < n; i++ {
				if err := m.PartitionsByUserEndpoint[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseEndpoint) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Host = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Host = v
	}
	{
		v, err := r.ReadUint16()
		if err != nil {
			return err
		}
		m.Port = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseEndpointToPartitions) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if err := m.UserEndpoint.decode(r, version); err != nil {
		return err
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.ActivePartitions = make([]StreamsGroupHeartbeatResponseTopicPartition, n)
			for i := 0; i < n; i++ {
				if err := m.ActivePartitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.StandbyPartitions = make([]StreamsGroupHeartbeatResponseTopicPartition, n)
			for i := 0; i < n; i++ {
				if err := m.StandbyPartitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseStatus) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.StatusCode = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.StatusDetail = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.StatusDetail = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseTaskIds) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.SubtopologyId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.SubtopologyId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.Partitions[i] = v
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseTopicPartition) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Topic = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Topic = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.Partitions[i] = v
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	if flexible {
		w.WriteCompactString(m.MemberId)
	} else {
		w.WriteString(m.MemberId)
	}
	w.WriteInt32(m.MemberEpoch)
	w.WriteInt32(m.HeartbeatIntervalMs)
	w.WriteInt32(m.AcceptableRecoveryLag)
	w.WriteInt32(m.TaskOffsetIntervalMs)
	{
		if m.Status == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.Status)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.Status[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	{
		if m.ActiveTasks == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.ActiveTasks)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.ActiveTasks[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	{
		if m.StandbyTasks == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.StandbyTasks)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.StandbyTasks[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	{
		if m.WarmupTasks == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.WarmupTasks)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.WarmupTasks[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	w.WriteInt32(m.EndpointInformationEpoch)
	{
		if m.PartitionsByUserEndpoint == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.PartitionsByUserEndpoint)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.PartitionsByUserEndpoint[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseEndpoint) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Host)
	} else {
		w.WriteString(m.Host)
	}
	w.WriteUint16(m.Port)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseEndpointToPartitions) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if err := m.UserEndpoint.encode(w, version); err != nil {
		return err
	}
	{
		n := len(m.ActivePartitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.ActivePartitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.StandbyPartitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.StandbyPartitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseStatus) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt8(m.StatusCode)
	if flexible {
		w.WriteCompactString(m.StatusDetail)
	} else {
		w.WriteString(m.StatusDetail)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseTaskIds) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.SubtopologyId)
	} else {
		w.WriteString(m.SubtopologyId)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt32(m.Partitions[i])
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupHeartbeatResponseTopicPartition) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Topic)
	} else {
		w.WriteString(m.Topic)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt32(m.Partitions[i])
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
