// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type StreamsGroupDescribeResponse struct {
	ThrottleTimeMs int32
	Groups         []StreamsGroupDescribeResponseDescribedGroup
}

type StreamsGroupDescribeResponseAssignment struct {
	ActiveTasks  []StreamsGroupDescribeResponseTaskIds
	StandbyTasks []StreamsGroupDescribeResponseTaskIds
	WarmupTasks  []StreamsGroupDescribeResponseTaskIds
}

type StreamsGroupDescribeResponseDescribedGroup struct {
	ErrorCode            int16
	ErrorMessage         *string
	GroupId              string
	GroupState           string
	GroupEpoch           int32
	AssignmentEpoch      int32
	Topology             StreamsGroupDescribeResponseTopology
	Members              []StreamsGroupDescribeResponseMember
	AuthorizedOperations int32
}

type StreamsGroupDescribeResponseEndpoint struct {
	Host string
	Port uint16
}

type StreamsGroupDescribeResponseKeyValue struct {
	Key   string
	Value string
}

type StreamsGroupDescribeResponseMember struct {
	MemberId         string
	MemberEpoch      int32
	InstanceId       *string
	RackId           *string
	ClientId         string
	ClientHost       string
	TopologyEpoch    int32
	ProcessId        string
	UserEndpoint     StreamsGroupDescribeResponseEndpoint
	ClientTags       []StreamsGroupDescribeResponseKeyValue
	TaskOffsets      []StreamsGroupDescribeResponseTaskOffset
	TaskEndOffsets   []StreamsGroupDescribeResponseTaskOffset
	Assignment       StreamsGroupDescribeResponseAssignment
	TargetAssignment StreamsGroupDescribeResponseAssignment
	IsClassic        bool
}

type StreamsGroupDescribeResponseSubtopology struct {
	SubtopologyId           string
	SourceTopics            []string
	RepartitionSinkTopics   []string
	StateChangelogTopics    []StreamsGroupDescribeResponseTopicInfo
	RepartitionSourceTopics []StreamsGroupDescribeResponseTopicInfo
}

type StreamsGroupDescribeResponseTaskIds struct {
	SubtopologyId string
	Partitions    []int32
}

type StreamsGroupDescribeResponseTaskOffset struct {
	SubtopologyId string
	Partition     int32
	Offset        int64
}

type StreamsGroupDescribeResponseTopicInfo struct {
	Name              string
	Partitions        int32
	ReplicationFactor int16
	TopicConfigs      []StreamsGroupDescribeResponseKeyValue
}

type StreamsGroupDescribeResponseTopology struct {
	Epoch         int32
	Subtopologies []StreamsGroupDescribeResponseSubtopology
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *StreamsGroupDescribeResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("StreamsGroupDescribeResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("StreamsGroupDescribeResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *StreamsGroupDescribeResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("StreamsGroupDescribeResponse v%d: %w", version, err)
	}
	return nil
}

func (m *StreamsGroupDescribeResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Groups = make([]StreamsGroupDescribeResponseDescribedGroup, n)
			for i := 0; i < n; i++ {
				if err := m.Groups[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseAssignment) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.ActiveTasks = make([]StreamsGroupDescribeResponseTaskIds, n)
			for i := 0; i < n; i++ {
				if err := m.ActiveTasks[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.StandbyTasks = make([]StreamsGroupDescribeResponseTaskIds, n)
			for i := 0; i < n; i++ {
				if err := m.StandbyTasks[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.WarmupTasks = make([]StreamsGroupDescribeResponseTaskIds, n)
			for i := 0; i < n; i++ {
				if err := m.WarmupTasks[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseDescribedGroup) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.ErrorMessage = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupId = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupState = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupState = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.GroupEpoch = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.AssignmentEpoch = v
	}
	if err := m.Topology.decode(r, version); err != nil {
		return err
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Members = make([]StreamsGroupDescribeResponseMember, n)
			for i := 0; i < n; i++ {
				if err := m.Members[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.AuthorizedOperations = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseEndpoint) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Host = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Host = v
	}
	{
		v, err := r.ReadUint16()
		if err != nil {
			return err
		}
		m.Port = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseKeyValue) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Key = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Key = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Value = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Value = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseMember) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.MemberId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.MemberId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.MemberEpoch = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.InstanceId = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.InstanceId = v
	}
	if flexible {
		v, err := r.ReadCompactNullableString()
		if err != nil {
			return err
		}
		m.RackId = v
	} else {
		v, err := r.ReadNullableString()
		if err != nil {
			return err
		}
		m.RackId = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ClientId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ClientId = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ClientHost = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ClientHost = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.TopologyEpoch = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.ProcessId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.ProcessId = v
	}
	if err := m.UserEndpoint.decode(r, version); err != nil {
		return err
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.ClientTags = make([]StreamsGroupDescribeResponseKeyValue, n)
			for i := 0; i < n; i++ {
				if err := m.ClientTags[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.TaskOffsets = make([]StreamsGroupDescribeResponseTaskOffset, n)
			for i := 0; i < n; i++ {
				if err := m.TaskOffsets[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.TaskEndOffsets = make([]StreamsGroupDescribeResponseTaskOffset, n)
			for i := 0; i < n; i++ {
				if err := m.TaskEndOffsets[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if err := m.Assignment.decode(r, version); err != nil {
		return err
	}
	if err := m.TargetAssignment.decode(r, version); err != nil {
		return err
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.IsClassic = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseSubtopology) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.SubtopologyId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.SubtopologyId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.SourceTopics = make([]string, n)
			for i := 0; i < n; i++ {
				if flexible {
					v, err := r.ReadCompactString()
					if err != nil {
						return err
					}
					m.SourceTopics[i] = v
				} else {
					v, err := r.ReadString()
					if err != nil {
						return err
					}
					m.SourceTopics[i] = v
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.RepartitionSinkTopics = make([]string, n)
			for i := 0; i < n; i++ {
				if flexible {
					v, err := r.ReadCompactString()
					if err != nil {
						return err
					}
					m.RepartitionSinkTopics[i] = v
				} else {
					v, err := r.ReadString()
					if err != nil {
						return err
					}
					m.RepartitionSinkTopics[i] = v
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.StateChangelogTopics = make([]StreamsGroupDescribeResponseTopicInfo, n)
			for i := 0; i < n; i++ {
				if err := m.StateChangelogTopics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.RepartitionSourceTopics = make([]StreamsGroupDescribeResponseTopicInfo, n)
			for i := 0; i < n; i++ {
				if err := m.RepartitionSourceTopics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseTaskIds) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.SubtopologyId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.SubtopologyId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]int32, n)
			for i := 0; i < n; i++ {
				{
					v, err := r.ReadInt32()
					if err != nil {
						return err
					}
					m.Partitions[i] = v
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseTaskOffset) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.SubtopologyId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.SubtopologyId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Partition = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.Offset = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseTopicInfo) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Partitions = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ReplicationFactor = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.TopicConfigs = make([]StreamsGroupDescribeResponseKeyValue, n)
			for i := 0; i < n; i++ {
				if err := m.TopicConfigs[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponseTopology) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Epoch = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Subtopologies = make([]StreamsGroupDescribeResponseSubtopology, n)
			for i := 0; i < n; i++ {
				if err := m.Subtopologies[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *StreamsGroupDescribeResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	{
		n := len(m.Groups)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Groups[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseAssignment) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		n := len(m.ActiveTasks)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.ActiveTasks[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.StandbyTasks)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.StandbyTasks[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.WarmupTasks)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.WarmupTasks[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseDescribedGroup) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteCompactNullableString(m.ErrorMessage)
	} else {
		w.WriteNullableString(m.ErrorMessage)
	}
	if flexible {
		w.WriteCompactString(m.GroupId)
	} else {
		w.WriteString(m.GroupId)
	}
	if flexible {
		w.WriteCompactString(m.GroupState)
	} else {
		w.WriteString(m.GroupState)
	}
	w.WriteInt32(m.GroupEpoch)
	w.WriteInt32(m.AssignmentEpoch)
	if err := m.Topology.encode(w, version); err != nil {
		return err
	}
	{
		n := len(m.Members)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Members[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	w.WriteInt32(m.AuthorizedOperations)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseEndpoint) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Host)
	} else {
		w.WriteString(m.Host)
	}
	w.WriteUint16(m.Port)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseKeyValue) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Key)
	} else {
		w.WriteString(m.Key)
	}
	if flexible {
		w.WriteCompactString(m.Value)
	} else {
		w.WriteString(m.Value)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseMember) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.MemberId)
	} else {
		w.WriteString(m.MemberId)
	}
	w.WriteInt32(m.MemberEpoch)
	if flexible {
		w.WriteCompactNullableString(m.InstanceId)
	} else {
		w.WriteNullableString(m.InstanceId)
	}
	if flexible {
		w.WriteCompactNullableString(m.RackId)
	} else {
		w.WriteNullableString(m.RackId)
	}
	if flexible {
		w.WriteCompactString(m.ClientId)
	} else {
		w.WriteString(m.ClientId)
	}
	if flexible {
		w.WriteCompactString(m.ClientHost)
	} else {
		w.WriteString(m.ClientHost)
	}
	w.WriteInt32(m.TopologyEpoch)
	if flexible {
		w.WriteCompactString(m.ProcessId)
	} else {
		w.WriteString(m.ProcessId)
	}
	if err := m.UserEndpoint.encode(w, version); err != nil {
		return err
	}
	{
		n := len(m.ClientTags)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.ClientTags[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.TaskOffsets)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.TaskOffsets[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.TaskEndOffsets)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.TaskEndOffsets[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if err := m.Assignment.encode(w, version); err != nil {
		return err
	}
	if err := m.TargetAssignment.encode(w, version); err != nil {
		return err
	}
	w.WriteBool(m.IsClassic)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseSubtopology) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.SubtopologyId)
	} else {
		w.WriteString(m.SubtopologyId)
	}
	{
		n := len(m.SourceTopics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if flexible {
				w.WriteCompactString(m.SourceTopics[i])
			} else {
				w.WriteString(m.SourceTopics[i])
			}
		}
	}
	{
		n := len(m.RepartitionSinkTopics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if flexible {
				w.WriteCompactString(m.RepartitionSinkTopics[i])
			} else {
				w.WriteString(m.RepartitionSinkTopics[i])
			}
		}
	}
	{
		n := len(m.StateChangelogTopics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.StateChangelogTopics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	{
		n := len(m.RepartitionSourceTopics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.RepartitionSourceTopics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseTaskIds) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.SubtopologyId)
	} else {
		w.WriteString(m.SubtopologyId)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			w.WriteInt32(m.Partitions[i])
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseTaskOffset) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.SubtopologyId)
	} else {
		w.WriteString(m.SubtopologyId)
	}
	w.WriteInt32(m.Partition)
	w.WriteInt64(m.Offset)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseTopicInfo) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	w.WriteInt32(m.Partitions)
	w.WriteInt16(m.ReplicationFactor)
	{
		n := len(m.TopicConfigs)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.TopicConfigs[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *StreamsGroupDescribeResponseTopology) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.Epoch)
	{
		if m.Subtopologies == nil {
			if flexible {
				w.WriteCompactArrayLen(-1)
			} else {
				w.WriteArrayLen(-1)
			}
		} else {
			n := len(m.Subtopologies)
			if flexible {
				w.WriteCompactArrayLen(n)
			} else {
				w.WriteArrayLen(n)
			}
			for i := 0; i < n; i++ {
				if err := m.Subtopologies[i].encode(w, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
