// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type SyncGroupResponse struct {
	ThrottleTimeMs int32
	ErrorCode      int16
	ProtocolType   *string
	ProtocolName   *string
	Assignment     []byte
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *SyncGroupResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("SyncGroupResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("SyncGroupResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *SyncGroupResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("SyncGroupResponse v%d: %w", version, err)
	}
	return nil
}

func (m *SyncGroupResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.ThrottleTimeMs = v
		}
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.ProtocolType = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.ProtocolType = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.ProtocolType = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.ProtocolType = &s
			}
		}
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				v, err := r.ReadCompactNullableString()
				if err != nil {
					return err
				}
				m.ProtocolName = v
			} else {
				v, err := r.ReadNullableString()
				if err != nil {
					return err
				}
				m.ProtocolName = v
			}
		} else {
			if flexible {
				v, err := r.ReadCompactString()
				if err != nil {
					return err
				}
				s := v
				m.ProtocolName = &s
			} else {
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				s := v
				m.ProtocolName = &s
			}
		}
	}
	if flexible {
		v, err := r.ReadCompactBytes()
		if err != nil {
			return err
		}
		m.Assignment = v
	} else {
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.Assignment = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *SyncGroupResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 4
	_ = flexible
	if version >= 1 {
		w.WriteInt32(m.ThrottleTimeMs)
	}
	w.WriteInt16(m.ErrorCode)
	if version >= 5 {
		if version >= 5 {
			if flexible {
				w.WriteCompactNullableString(m.ProtocolType)
			} else {
				w.WriteNullableString(m.ProtocolType)
			}
		} else {
			if m.ProtocolType == nil {
				return fmt.Errorf("ProtocolType: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.ProtocolType)
			} else {
				w.WriteString(*m.ProtocolType)
			}
		}
	}
	if version >= 5 {
		if version >= 5 {
			if flexible {
				w.WriteCompactNullableString(m.ProtocolName)
			} else {
				w.WriteNullableString(m.ProtocolName)
			}
		} else {
			if m.ProtocolName == nil {
				return fmt.Errorf("ProtocolName: nil at non-nullable version")
			}
			if flexible {
				w.WriteCompactString(*m.ProtocolName)
			} else {
				w.WriteString(*m.ProtocolName)
			}
		}
	}
	if flexible {
		w.WriteCompactBytes(m.Assignment)
	} else {
		w.WriteBytes(m.Assignment)
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
