// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type UnregisterControllerRequest struct {
	ControllerId int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *UnregisterControllerRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("UnregisterControllerRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("UnregisterControllerRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *UnregisterControllerRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("UnregisterControllerRequest v%d: %w", version, err)
	}
	return nil
}

func (m *UnregisterControllerRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ControllerId = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *UnregisterControllerRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ControllerId)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
