// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type UpdateRaftVoterResponse struct {
	ThrottleTimeMs int32
	ErrorCode      int16
	CurrentLeader  UpdateRaftVoterResponseCurrentLeader
}

type UpdateRaftVoterResponseCurrentLeader struct {
	LeaderId    int32
	LeaderEpoch int32
	Host        string
	Port        int32
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *UpdateRaftVoterResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("UpdateRaftVoterResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("UpdateRaftVoterResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *UpdateRaftVoterResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("UpdateRaftVoterResponse v%d: %w", version, err)
	}
	return nil
}

func (m *UpdateRaftVoterResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		if err := r.ReadTaggedFields(func(tag uint64, sub *Reader) error {
			switch tag {
			case 0:
				if !(true) {
					return nil
				}
				if err := m.CurrentLeader.decode(sub, version); err != nil {
					return err
				}
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func (m *UpdateRaftVoterResponseCurrentLeader) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderId = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderEpoch = v
	}
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Host = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Host = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Port = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *UpdateRaftVoterResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.ThrottleTimeMs)
	w.WriteInt16(m.ErrorCode)
	if flexible {
		var tfs []TaggedField
		if true {
			sub := NewWriter()
			if err := m.CurrentLeader.encode(sub, version); err != nil {
				return err
			}
			tfs = append(tfs, TaggedField{Tag: 0, Body: sub.Bytes()})
		}
		w.WriteTaggedFields(tfs)
	}
	return nil
}

func (m *UpdateRaftVoterResponseCurrentLeader) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.LeaderId)
	w.WriteInt32(m.LeaderEpoch)
	if flexible {
		w.WriteCompactString(m.Host)
	} else {
		w.WriteString(m.Host)
	}
	w.WriteInt32(m.Port)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
