// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type WriteShareGroupStateRequest struct {
	GroupId string
	Topics  []WriteShareGroupStateRequestWriteStateData
}

type WriteShareGroupStateRequestPartitionData struct {
	Partition             int32
	StateEpoch            int32
	LeaderEpoch           int32
	StartOffset           int64
	DeliveryCompleteCount int32
	StateBatches          []WriteShareGroupStateRequestStateBatch
}

type WriteShareGroupStateRequestStateBatch struct {
	FirstOffset   int64
	LastOffset    int64
	DeliveryState int8
	DeliveryCount int16
}

type WriteShareGroupStateRequestWriteStateData struct {
	TopicId    [16]byte
	Partitions []WriteShareGroupStateRequestPartitionData
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *WriteShareGroupStateRequest) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("WriteShareGroupStateRequest v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("WriteShareGroupStateRequest v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *WriteShareGroupStateRequest) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("WriteShareGroupStateRequest v%d: %w", version, err)
	}
	return nil
}

func (m *WriteShareGroupStateRequest) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.GroupId = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.GroupId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]WriteShareGroupStateRequestWriteStateData, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *WriteShareGroupStateRequestPartitionData) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.Partition = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.StateEpoch = v
	}
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.LeaderEpoch = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.StartOffset = v
	}
	if version >= 1 {
		{
			v, err := r.ReadInt32()
			if err != nil {
				return err
			}
			m.DeliveryCompleteCount = v
		}
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.StateBatches = make([]WriteShareGroupStateRequestStateBatch, n)
			for i := 0; i < n; i++ {
				if err := m.StateBatches[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *WriteShareGroupStateRequestStateBatch) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.FirstOffset = v
	}
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.LastOffset = v
	}
	{
		v, err := r.ReadInt8()
		if err != nil {
			return err
		}
		m.DeliveryState = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.DeliveryCount = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *WriteShareGroupStateRequestWriteStateData) decode(r *Reader, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	{
		v, err := r.ReadUUID()
		if err != nil {
			return err
		}
		m.TopicId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]WriteShareGroupStateRequestPartitionData, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *WriteShareGroupStateRequest) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	if flexible {
		w.WriteCompactString(m.GroupId)
	} else {
		w.WriteString(m.GroupId)
	}
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *WriteShareGroupStateRequestPartitionData) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt32(m.Partition)
	w.WriteInt32(m.StateEpoch)
	w.WriteInt32(m.LeaderEpoch)
	w.WriteInt64(m.StartOffset)
	if version >= 1 {
		w.WriteInt32(m.DeliveryCompleteCount)
	}
	{
		n := len(m.StateBatches)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.StateBatches[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *WriteShareGroupStateRequestStateBatch) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteInt64(m.FirstOffset)
	w.WriteInt64(m.LastOffset)
	w.WriteInt8(m.DeliveryState)
	w.WriteInt16(m.DeliveryCount)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *WriteShareGroupStateRequestWriteStateData) encode(w *Writer, version int16) error {
	_ = version
	flexible := true
	_ = flexible
	w.WriteUUID(m.TopicId)
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
