// Code generated by cmd/kafkagen. DO NOT EDIT.

package kafkaproto

import (
	"fmt"
)

type WriteTxnMarkersResponse struct {
	Markers []WriteTxnMarkersResponseWritableTxnMarkerResult
}

type WriteTxnMarkersResponseWritableTxnMarkerPartitionResult struct {
	PartitionIndex int32
	ErrorCode      int16
}

type WriteTxnMarkersResponseWritableTxnMarkerResult struct {
	ProducerId int64
	Topics     []WriteTxnMarkersResponseWritableTxnMarkerTopicResult
}

type WriteTxnMarkersResponseWritableTxnMarkerTopicResult struct {
	Name       string
	Partitions []WriteTxnMarkersResponseWritableTxnMarkerPartitionResult
}

// Decode reads m from r at the given protocol version. r must be positioned
// at the start of the message body (after any request/response header) and
// must contain exactly one message — trailing bytes return ErrTrailingBytes.
func (m *WriteTxnMarkersResponse) Decode(r *Reader, version int16) error {
	if err := m.decode(r, version); err != nil {
		return fmt.Errorf("WriteTxnMarkersResponse v%d: %w", version, err)
	}
	if n := r.Remaining(); n > 0 {
		return fmt.Errorf("WriteTxnMarkersResponse v%d: %w (%d byte(s) left)", version, ErrTrailingBytes, n)
	}
	return nil
}

// Encode serializes m into w at the given protocol version (the bytes
// appended are the message body only, no request/response header).
func (m *WriteTxnMarkersResponse) Encode(w *Writer, version int16) error {
	if err := m.encode(w, version); err != nil {
		return fmt.Errorf("WriteTxnMarkersResponse v%d: %w", version, err)
	}
	return nil
}

func (m *WriteTxnMarkersResponse) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Markers = make([]WriteTxnMarkersResponseWritableTxnMarkerResult, n)
			for i := 0; i < n; i++ {
				if err := m.Markers[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *WriteTxnMarkersResponseWritableTxnMarkerPartitionResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		v, err := r.ReadInt32()
		if err != nil {
			return err
		}
		m.PartitionIndex = v
	}
	{
		v, err := r.ReadInt16()
		if err != nil {
			return err
		}
		m.ErrorCode = v
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *WriteTxnMarkersResponseWritableTxnMarkerResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		v, err := r.ReadInt64()
		if err != nil {
			return err
		}
		m.ProducerId = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Topics = make([]WriteTxnMarkersResponseWritableTxnMarkerTopicResult, n)
			for i := 0; i < n; i++ {
				if err := m.Topics[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *WriteTxnMarkersResponseWritableTxnMarkerTopicResult) decode(r *Reader, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		v, err := r.ReadCompactString()
		if err != nil {
			return err
		}
		m.Name = v
	} else {
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		var n int
		var err error
		if flexible {
			n, err = r.ReadCompactArrayLen()
		} else {
			n, err = r.ReadArrayLen()
		}
		if err != nil {
			return err
		}
		if n >= 0 {
			m.Partitions = make([]WriteTxnMarkersResponseWritableTxnMarkerPartitionResult, n)
			for i := 0; i < n; i++ {
				if err := m.Partitions[i].decode(r, version); err != nil {
					return err
				}
			}
		}
	}
	if flexible {
		if err := r.ReadTaggedFields(nil); err != nil {
			return err
		}
	}
	return nil
}

func (m *WriteTxnMarkersResponse) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	{
		n := len(m.Markers)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Markers[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *WriteTxnMarkersResponseWritableTxnMarkerPartitionResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	w.WriteInt32(m.PartitionIndex)
	w.WriteInt16(m.ErrorCode)
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *WriteTxnMarkersResponseWritableTxnMarkerResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	w.WriteInt64(m.ProducerId)
	{
		n := len(m.Topics)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Topics[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}

func (m *WriteTxnMarkersResponseWritableTxnMarkerTopicResult) encode(w *Writer, version int16) error {
	_ = version
	flexible := version >= 1
	_ = flexible
	if flexible {
		w.WriteCompactString(m.Name)
	} else {
		w.WriteString(m.Name)
	}
	{
		n := len(m.Partitions)
		if flexible {
			w.WriteCompactArrayLen(n)
		} else {
			w.WriteArrayLen(n)
		}
		for i := 0; i < n; i++ {
			if err := m.Partitions[i].encode(w, version); err != nil {
				return err
			}
		}
	}
	if flexible {
		w.WriteTaggedFields(nil)
	}
	return nil
}
