// Command kafkagen reads Kafka protocol message definitions from a directory
// of JSON specs and generates Go decoders into a target package directory.
//
// Each request/response/header/data spec produces one file (snake_case of the
// message name) with struct types and a Decode method. A dispatch.go file is
// also emitted with UnmarshalRequest and UnmarshalResponse top-level helpers.
//
//go:generate go run ./... -in ../../message -out ../../
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	var inDir, outDir string
	flag.StringVar(&inDir, "in", "message", "directory of Kafka JSON spec files")
	flag.StringVar(&outDir, "out", "kafkaproto", "directory to write generated Go files into")
	flag.Parse()

	if err := run(inDir, outDir); err != nil {
		log.Fatal(err)
	}
}

func run(inDir, outDir string) error {
	entries, err := os.ReadDir(inDir)
	if err != nil {
		return fmt.Errorf("read %s: %w", inDir, err)
	}

	// Clean previously generated files (anything tagged with our header).
	if err := cleanGenerated(outDir); err != nil {
		return err
	}

	var specs []*Spec
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		path := filepath.Join(inDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		spec, err := ParseSpec(data)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		if spec.Valid.None {
			// "validVersions": "none" — message is deprecated/unsupported.
			continue
		}
		specs = append(specs, spec)
	}

	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })

	for _, spec := range specs {
		out, err := EmitMessageFile(spec)
		if err != nil {
			return fmt.Errorf("emit %s: %w", spec.Name, err)
		}
		path := filepath.Join(outDir, snakeCase(spec.Name)+".go")
		if err := os.WriteFile(path, out, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	dispatch, err := EmitDispatch(specs)
	if err != nil {
		return fmt.Errorf("emit dispatch: %w", err)
	}
	path := filepath.Join(outDir, "dispatch.go")
	if err := os.WriteFile(path, dispatch, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	log.Printf("kafkagen: wrote %d message files + dispatch.go", len(specs))
	return nil
}

const generatedHeader = "// Code generated by cmd/kafkagen. DO NOT EDIT."

// cleanGenerated removes every .go file in outDir that begins with our generated
// header. Hand-written files (reader.go, gen.go, ...) are left alone.
func cleanGenerated(outDir string) error {
	entries, err := os.ReadDir(outDir)
	if err != nil {
		return fmt.Errorf("read %s: %w", outDir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		path := filepath.Join(outDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if bytes.HasPrefix(data, []byte(generatedHeader)) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

func snakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func gofmt(src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		// Return the unformatted source alongside the error so the user can see
		// which line tripped gofmt; helps debug generator bugs.
		return src, fmt.Errorf("gofmt: %w\n--- source ---\n%s", err, src)
	}
	return out, nil
}

// EmitDispatch generates the top-level UnmarshalRequest / UnmarshalResponse helpers.
func EmitDispatch(specs []*Spec) ([]byte, error) {
	e := &emitter{}
	e.line(generatedHeader)
	e.line("")
	e.line("package kafkaproto")
	e.line("")
	e.line("import \"fmt\"")
	e.line("")
	e.line("// Message is implemented by every generated request/response struct.")
	e.line("type Message interface {")
	e.line("\tDecode(r *Reader, version int16) error")
	e.line("\tEncode(w *Writer, version int16) error")
	e.line("}")
	e.line("")

	emitDispatchFn(e, "UnmarshalRequest", "request", specs)
	emitDispatchFn(e, "UnmarshalResponse", "response", specs)

	emitErrorResponseFn(e, specs)

	emitRequestHeaderCodec(e, specs)
	emitResponseHeaderCodec(e, specs)

	return gofmt(e.buf.Bytes())
}

// emitRequestHeaderCodec writes free-standing ReadRequestHeader and
// WriteRequestHeader helpers. For flexible (apiKey, apiVersion) combinations
// the read path consumes the trailing tagged-fields count and the write path
// emits an empty tagged-fields block. Flexibility is determined per apiKey
// from the request spec's flexibleVersions.
func emitRequestHeaderCodec(e *emitter, specs []*Spec) {
	e.line("// ReadRequestHeader decodes a Kafka request header. For flexible (apiKey,")
	e.line("// apiVersion) combinations it also consumes the trailing tagged-fields count,")
	e.line("// leaving r positioned at the start of the request body.")
	e.line("func ReadRequestHeader(r *Reader) (apiKey int16, apiVersion int16, corrID int32, clientID *string, err error) {")
	e.line("\tapiKey, err = r.ReadInt16()")
	e.line("\tif err != nil { return }")
	e.line("\tapiVersion, err = r.ReadInt16()")
	e.line("\tif err != nil { return }")
	e.line("\tcorrID, err = r.ReadInt32()")
	e.line("\tif err != nil { return }")
	e.line("\tclientID, err = r.ReadNullableString()")
	e.line("\tif err != nil { return }")
	e.line("\tif requestHeaderFlexible(apiKey, apiVersion) {")
	e.line("\t\tif err = r.ReadTaggedFields(nil); err != nil { return }")
	e.line("\t}")
	e.line("\treturn")
	e.line("}")
	e.line("")
	e.line("// WriteRequestHeader encodes a Kafka request header (apiKey, apiVersion,")
	e.line("// correlation id, client id). For flexible (apiKey, apiVersion) combinations")
	e.line("// it also writes an empty tagged-fields block.")
	e.line("func WriteRequestHeader(w *Writer, apiKey int16, apiVersion int16, corrID int32, clientID *string) {")
	e.line("\tw.WriteInt16(apiKey)")
	e.line("\tw.WriteInt16(apiVersion)")
	e.line("\tw.WriteInt32(corrID)")
	e.line("\tw.WriteNullableString(clientID)")
	e.line("\tif requestHeaderFlexible(apiKey, apiVersion) {")
	e.line("\t\tw.WriteTaggedFields(nil)")
	e.line("\t}")
	e.line("}")
	e.line("")
	emitFlexibleSwitch(e, "requestHeaderFlexible", "request", specs)
}

// emitResponseHeaderCodec writes free-standing ReadResponseHeader and
// WriteResponseHeader helpers. For flexible (apiKey, apiVersion) combinations
// the read path consumes the trailing tagged-fields count and the write path
// emits an empty tagged-fields block. Flexibility is determined per apiKey
// from the response spec's flexibleVersions.
func emitResponseHeaderCodec(e *emitter, specs []*Spec) {
	e.line("// ReadResponseHeader decodes a Kafka response header. The wire form is just")
	e.line("// the correlation id (plus a tagged-fields count for flexible apiVersions),")
	e.line("// so the caller supplies a lookup that maps the just-read corrID back to the")
	e.line("// (apiKey, apiVersion) of the original request — typically by consulting an")
	e.line("// in-flight table — which is what we need to decide whether the header is")
	e.line("// flexible. A non-nil error from lookup is returned as-is.")
	e.line("func ReadResponseHeader(r *Reader, lookup func(corrID int32) (apiKey, apiVersion int16, err error)) (corrID int32, apiKey int16, apiVersion int16, err error) {")
	e.line("\tcorrID, err = r.ReadInt32()")
	e.line("\tif err != nil { return }")
	e.line("\tapiKey, apiVersion, err = lookup(corrID)")
	e.line("\tif err != nil { return }")
	e.line("\tif responseHeaderFlexible(apiKey, apiVersion) {")
	e.line("\t\tif err = r.ReadTaggedFields(nil); err != nil { return }")
	e.line("\t}")
	e.line("\treturn")
	e.line("}")
	e.line("")
	e.line("// WriteResponseHeader encodes a Kafka response header (correlation id, plus")
	e.line("// an empty tagged-fields block for flexible apiVersions). apiKey and")
	e.line("// apiVersion are only used to decide whether the header is flexible.")
	e.line("func WriteResponseHeader(w *Writer, corrID int32, apiKey int16, apiVersion int16) {")
	e.line("\tw.WriteInt32(corrID)")
	e.line("\tif responseHeaderFlexible(apiKey, apiVersion) {")
	e.line("\t\tw.WriteTaggedFields(nil)")
	e.line("\t}")
	e.line("}")
	e.line("")
	emitFlexibleSwitch(e, "responseHeaderFlexible", "response", specs)
}

func emitFlexibleSwitch(e *emitter, fnName, kind string, specs []*Spec) {
	byKey := map[int]*Spec{}
	for _, s := range specs {
		if s.Type != kind || !s.HasAPIKey {
			continue
		}
		byKey[s.APIKey] = s
	}
	keys := make([]int, 0, len(byKey))
	for k := range byKey {
		keys = append(keys, k)
	}
	sort.Ints(keys)

	e.line("func %s(apiKey, apiVersion int16) bool {", fnName)
	e.line("\t_ = apiVersion")
	e.line("\tswitch apiKey {")
	for _, k := range keys {
		s := byKey[k]
		// KIP-511: the ApiVersions response header is pinned to v0 so an old
		// client can still parse ErrorCode when the broker speaks a newer
		// protocol than it understands. The request side is unaffected.
		if kind == "response" && k == 18 {
			e.line("\tcase %d: // %s — KIP-511: response header pinned to v0", k, s.Name)
			e.line("\t\treturn false")
			continue
		}
		cond := s.Flexible.Condition("apiVersion")
		e.line("\tcase %d: // %s", k, s.Name)
		e.line("\t\treturn %s", cond)
	}
	e.line("\t}")
	e.line("\treturn false")
	e.line("}")
	e.line("")
}

// topLevelField returns the top-level field of s with the given name, or nil.
func topLevelField(s *Spec, name string) *Field {
	for _, f := range s.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

// elementField returns the named field on a struct-typed array element, or nil.
func elementField(s *Spec, arr *Field, name string) *Field {
	if arr.Kind != KindArray || arr.Elem == nil || arr.Elem.Kind != KindStruct {
		return nil
	}
	st := s.Structs[arr.Elem.StructName]
	if st == nil {
		return nil
	}
	for _, f := range st.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

// arrayAction describes a single top-level response array we can populate from
// the matching top-level request array of the same name. arrayName is the
// field name in both structs. condition gates whether the iteration is
// meaningful at apiVersion (the array, its matching request array, and the
// element's ErrorCode field must all be in scope). msgCondition is non-empty
// only when the response element has an ErrorMessage field; it gates the
// assignment to that field inside the loop.
type arrayAction struct {
	arrayName    string
	respElemType string
	condition    string
	msgCondition string
	// scalarCopies lists scalar fields present on both element structs (by
	// matching name and Kind/Go type) that should be copied from the request
	// item into the response item.
	scalarCopies []string
}

// responseEntry collects everything we need to emit one case clause of
// ErrorResponse: the request type to type-switch on, the response struct to
// construct, and the actions (top-level + per-array) that populate it.
type responseEntry struct {
	req, resp *Spec
	// outerCondition gates the entire case body. It is the disjunction of
	// every action's condition (so at least one action fires whenever it
	// evaluates true). "true" means unconditional.
	outerCondition string
	// topCondition is non-empty iff the response has a top-level ErrorCode
	// field; it gates `m.ErrorCode = errorCode`.
	topCondition string
	// topMsgCondition is non-empty iff the response has a top-level
	// ErrorMessage field; it gates `m.ErrorMessage = errorMessage`.
	topMsgCondition string
	arrays          []arrayAction
}

// isCopyableScalar reports whether fields of this Kind can be assigned
// directly from a request struct to a response struct (no allocation or
// conversion needed).
func isCopyableScalar(k FieldKind) bool {
	switch k {
	case KindBool, KindInt8, KindInt16, KindUint16, KindInt32, KindUint32,
		KindInt64, KindFloat64, KindString, KindUUID:
		return true
	}
	return false
}

// buildEntry computes the responseEntry for an (apiKey) request/response pair,
// or returns false if no error information can be conveyed.
func buildEntry(req, resp *Spec) (responseEntry, bool) {
	ent := responseEntry{req: req, resp: resp}
	var conds []string

	// Top-level ErrorCode.
	if ec := topLevelField(resp, "ErrorCode"); ec != nil && ec.Kind == KindInt16 {
		if rng := resp.Valid.Intersect(ec.Versions); !rng.None {
			ent.topCondition = rng.Condition("apiVersion")
			conds = append(conds, ent.topCondition)
			// Top-level ErrorMessage is only meaningful together with
			// top-level ErrorCode.
			if em := topLevelField(resp, "ErrorMessage"); em != nil && em.Kind == KindString && !em.Nullable.None {
				if mrng := rng.Intersect(em.Versions); !mrng.None {
					ent.topMsgCondition = mrng.Condition("apiVersion")
				}
			}
		}
	}

	// Top-level array fields with a matching request array, where the element
	// carries an ErrorCode int16. Only one level of nesting is considered.
	for _, rf := range resp.Fields {
		if rf.Kind != KindArray || rf.Elem == nil || rf.Elem.Kind != KindStruct {
			continue
		}
		respEC := elementField(resp, rf, "ErrorCode")
		if respEC == nil || respEC.Kind != KindInt16 {
			continue
		}
		qf := topLevelField(req, rf.Name)
		if qf == nil || qf.Kind != KindArray || qf.Elem == nil || qf.Elem.Kind != KindStruct {
			continue
		}
		// Combined range: response array in scope, request array in scope,
		// and the element's ErrorCode in scope.
		rng := resp.Valid.Intersect(rf.Versions).Intersect(qf.Versions).Intersect(respEC.Versions)
		if rng.None {
			continue
		}
		act := arrayAction{
			arrayName:    rf.Name,
			respElemType: goTypeName(resp.Name, rf.Elem.StructName),
			condition:    rng.Condition("apiVersion"),
		}
		if em := elementField(resp, rf, "ErrorMessage"); em != nil && em.Kind == KindString && !em.Nullable.None {
			if mrng := rng.Intersect(em.Versions); !mrng.None {
				act.msgCondition = mrng.Condition("apiVersion")
			}
		}
		// Identify scalar fields that exist on both element structs with the
		// same name and Go type — those get copied from the request item to
		// the response item.
		respElemS := resp.Structs[rf.Elem.StructName]
		reqElemS := req.Structs[qf.Elem.StructName]
		if respElemS != nil && reqElemS != nil {
			reqByName := map[string]*Field{}
			for _, x := range reqElemS.Fields {
				reqByName[x.Name] = x
			}
			for _, ef := range respElemS.Fields {
				if ef.Name == "ErrorCode" || ef.Name == "ErrorMessage" {
					continue
				}
				if !isCopyableScalar(ef.Kind) {
					continue
				}
				qef := reqByName[ef.Name]
				if qef == nil || qef.Kind != ef.Kind {
					continue
				}
				if goFieldType(resp, ef) != goFieldType(req, qef) {
					continue
				}
				act.scalarCopies = append(act.scalarCopies, ef.Name)
			}
		}
		ent.arrays = append(ent.arrays, act)
		conds = append(conds, act.condition)
	}

	if ent.topCondition == "" && len(ent.arrays) == 0 {
		return responseEntry{}, false
	}

	// Build the outer condition as the OR of every action's condition.
	// Collapse to "true" when any action fires unconditionally.
	outer := strings.Join(uniqueNonEmpty(conds), " || ")
	for _, c := range conds {
		if c == "true" {
			outer = "true"
			break
		}
	}
	ent.outerCondition = outer
	return ent, true
}

func uniqueNonEmpty(in []string) []string {
	seen := map[string]bool{}
	out := in[:0]
	for _, s := range in {
		if s == "" || seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}

// emitErrorResponseFn writes the ErrorResponse helper, which builds a response
// for the supplied request with errorCode (and errorMessage when present)
// applied to every top-level error field the response exposes — both a
// top-level ErrorCode/ErrorMessage if the response has them, and one entry
// per request item for each top-level request array that matches a top-level
// response array (by name) whose elements carry an ErrorCode field. Each
// per-item copy also propagates any scalar fields the request and response
// elements share by name (e.g. the topic Name on CreateTopics).
//
// A request type is omitted from the switch when no top-level error can be
// expressed for it — most commonly when the response error lives deeper than
// one level of nesting, or when the request array name differs from the
// response array name. A small set of hand-coded special cases covers
// well-known field-name mismatches (see specialCaseEmitters).
func emitErrorResponseFn(e *emitter, specs []*Spec) {
	// Pair up request and response by apiKey.
	type pair struct{ req, resp *Spec }
	pairs := map[int]pair{}
	for _, s := range specs {
		if !s.HasAPIKey {
			continue
		}
		p := pairs[s.APIKey]
		switch s.Type {
		case "request":
			p.req = s
		case "response":
			p.resp = s
		}
		pairs[s.APIKey] = p
	}

	entries := map[int]responseEntry{}
	for k, p := range pairs {
		if p.req == nil || p.resp == nil {
			continue
		}
		// Hand-coded cases own their case clause entirely; skip generic logic
		// so we don't emit two case clauses for the same request type.
		if _, ok := specialCaseEmitters[k]; ok {
			continue
		}
		ent, ok := buildEntry(p.req, p.resp)
		if !ok {
			continue
		}
		entries[k] = ent
	}

	keySeen := map[int]bool{}
	var keys []int
	for k := range entries {
		if !keySeen[k] {
			keySeen[k] = true
			keys = append(keys, k)
		}
	}
	for k := range specialCaseEmitters {
		if _, ok := pairs[k]; !ok {
			continue
		}
		if !keySeen[k] {
			keySeen[k] = true
			keys = append(keys, k)
		}
	}
	sort.Ints(keys)

	e.line("// ErrorResponse synthesises an error response for req at apiVersion, with")
	e.line("// errorCode applied to every top-level error field the response exposes:")
	e.line("// the response's top-level ErrorCode (and ErrorMessage) if present, and one")
	e.line("// entry per request item for each top-level request array that matches a")
	e.line("// top-level response array by name and whose elements carry an ErrorCode.")
	e.line("// Each per-item copy propagates any scalar fields the request and response")
	e.line("// elements share by name. Returns an error when no response is paired with")
	e.line("// req's type, or when apiVersion is outside the range in which the response")
	e.line("// can carry the error on the wire.")
	e.line("func ErrorResponse(req Message, apiVersion int16, errorCode int16, errorMessage *string) (Message, error) {")
	e.line("\tswitch r := req.(type) {")
	for _, k := range keys {
		if fn, ok := specialCaseEmitters[k]; ok {
			p := pairs[k]
			fn(e, p.req, p.resp)
			continue
		}
		ent := entries[k]
		e.line("\tcase *%s:", ent.req.Name)
		// If we'll never reference r in this case body (no array actions), the
		// type switch still allows the unused binding — Go does not flag case
		// variables. But emitting a discard keeps the generated code obvious.
		if len(ent.arrays) == 0 {
			e.line("\t\t_ = r")
		}
		indent := "\t\t"
		if ent.outerCondition != "true" {
			e.line("\t\tif %s {", ent.outerCondition)
			indent = "\t\t\t"
		}
		e.line("%sm := &%s{}", indent, ent.resp.Name)
		emitEntryBody(e, ent, indent)
		e.line("%sreturn m, nil", indent)
		if ent.outerCondition != "true" {
			e.line("\t\t}")
		}
	}
	e.line("\t}")
	e.line("\treturn nil, fmt.Errorf(\"kafkaproto: no error response available for %%T at apiVersion %%d\", req, apiVersion)")
	e.line("}")
	e.line("")
}

// specialCaseEmitters holds apiKeys whose request/response field names don't
// line up well enough for the generic name-based matcher in buildEntry. Each
// entry owns its full case clause inside the ErrorResponse switch.
var specialCaseEmitters = map[int]func(e *emitter, req, resp *Spec){
	20: emitDeleteTopicsCase,
}

// emitDeleteTopicsCase hand-codes the DeleteTopics (apiKey 20) case. The
// request carries topics in `Topics` ([]DeleteTopicState, v6+) or
// `TopicNames` ([]string, v0-5), while the response always uses `Responses`
// ([]DeletableTopicResult) — three different field names, two different
// element shapes, so the generic name-match in buildEntry can't pair them
// up.
//
// Type names are taken from the parsed specs so a rename in the JSON catalog
// flows through; only the field routing (which request field feeds which
// response field at which versions) is fixed.
func emitDeleteTopicsCase(e *emitter, req, resp *Spec) {
	respArr := topLevelField(resp, "Responses")
	if respArr == nil || respArr.Elem == nil {
		return
	}
	elemType := goTypeName(resp.Name, respArr.Elem.StructName)

	topicsCond := req.Valid.Intersect(topLevelField(req, "Topics").Versions).
		Intersect(resp.Valid).Condition("apiVersion")
	namesCond := req.Valid.Intersect(topLevelField(req, "TopicNames").Versions).
		Intersect(resp.Valid).Condition("apiVersion")

	// ErrorMessage on the response element — version range intersected with
	// validVersions. Within the Topics branch this is always satisfied
	// (Topics is v6+, ErrorMessage is v5+); within the TopicNames branch it
	// gates on whether apiVersion has crossed into the ErrorMessage range.
	errMsgRange := resp.Valid
	if em := findElemField(resp, respArr, "ErrorMessage"); em != nil {
		errMsgRange = errMsgRange.Intersect(em.Versions)
	}
	namesMsgRange := errMsgRange.Intersect(topLevelField(req, "TopicNames").Versions)

	e.line("\tcase *%s:", req.Name)
	e.line("\t\tswitch {")
	e.line("\t\tcase %s:", topicsCond)
	e.line("\t\t\tm := &%s{}", resp.Name)
	e.line("\t\t\tm.Responses = make([]%s, len(r.Topics))", elemType)
	e.line("\t\t\tfor i0, it0 := range r.Topics {")
	e.line("\t\t\t\tm.Responses[i0].Name = it0.Name")
	e.line("\t\t\t\tm.Responses[i0].TopicId = it0.TopicId")
	e.line("\t\t\t\tm.Responses[i0].ErrorCode = errorCode")
	e.line("\t\t\t\tm.Responses[i0].ErrorMessage = errorMessage")
	e.line("\t\t\t}")
	e.line("\t\t\treturn m, nil")
	e.line("\t\tcase %s:", namesCond)
	e.line("\t\t\tm := &%s{}", resp.Name)
	e.line("\t\t\tm.Responses = make([]%s, len(r.TopicNames))", elemType)
	e.line("\t\t\tfor i0, name0 := range r.TopicNames {")
	e.line("\t\t\t\tm.Responses[i0].Name = &name0")
	e.line("\t\t\t\tm.Responses[i0].ErrorCode = errorCode")
	if !namesMsgRange.None {
		nmCond := namesMsgRange.Condition("apiVersion")
		if nmCond == "true" || nmCond == namesCond {
			e.line("\t\t\t\tm.Responses[i0].ErrorMessage = errorMessage")
		} else {
			e.line("\t\t\t\tif %s {", nmCond)
			e.line("\t\t\t\t\tm.Responses[i0].ErrorMessage = errorMessage")
			e.line("\t\t\t\t}")
		}
	}
	e.line("\t\t\t}")
	e.line("\t\t\treturn m, nil")
	e.line("\t\t}")
}

// findElemField looks up a named field on a struct-typed array element.
func findElemField(spec *Spec, arr *Field, name string) *Field {
	if arr == nil || arr.Elem == nil || arr.Elem.Kind != KindStruct {
		return nil
	}
	st := spec.Structs[arr.Elem.StructName]
	if st == nil {
		return nil
	}
	for _, f := range st.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

// emitEntryBody writes the populate statements inside a case, gating each
// action with its own condition when it's narrower than the outer condition.
func emitEntryBody(e *emitter, ent responseEntry, indent string) {
	// Top-level ErrorCode.
	if ent.topCondition != "" {
		emitGated(e, indent, ent.topCondition, ent.outerCondition, func(inner string) {
			e.line("%sm.ErrorCode = errorCode", inner)
			if ent.topMsgCondition != "" && ent.topMsgCondition == ent.topCondition {
				e.line("%sm.ErrorMessage = errorMessage", inner)
			}
		})
		// ErrorMessage with a strictly narrower range needs its own gate.
		if ent.topMsgCondition != "" && ent.topMsgCondition != ent.topCondition {
			emitGated(e, indent, ent.topMsgCondition, ent.outerCondition, func(inner string) {
				e.line("%sm.ErrorMessage = errorMessage", inner)
			})
		}
	}

	// Per-array iterations.
	for i, act := range ent.arrays {
		idx := fmt.Sprintf("i%d", i)
		item := fmt.Sprintf("it%d", i)
		emitGated(e, indent, act.condition, ent.outerCondition, func(inner string) {
			e.line("%sm.%s = make([]%s, len(r.%s))", inner, act.arrayName, act.respElemType, act.arrayName)
			if len(act.scalarCopies) == 0 {
				e.line("%sfor %s := range r.%s {", inner, idx, act.arrayName)
			} else {
				e.line("%sfor %s, %s := range r.%s {", inner, idx, item, act.arrayName)
			}
			body := inner + "\t"
			for _, name := range act.scalarCopies {
				e.line("%sm.%s[%s].%s = %s.%s", body, act.arrayName, idx, name, item, name)
			}
			e.line("%sm.%s[%s].ErrorCode = errorCode", body, act.arrayName, idx)
			if act.msgCondition != "" {
				if act.msgCondition == act.condition {
					e.line("%sm.%s[%s].ErrorMessage = errorMessage", body, act.arrayName, idx)
				} else {
					e.line("%sif %s {", body, act.msgCondition)
					e.line("%s\tm.%s[%s].ErrorMessage = errorMessage", body, act.arrayName, idx)
					e.line("%s}", body)
				}
			}
			e.line("%s}", inner)
		})
	}
}

// emitGated emits body inside an `if cond { ... }` block, unless cond is
// already implied by outer (or is trivially "true"), in which case body is
// emitted directly at indent.
func emitGated(e *emitter, indent, cond, outer string, body func(inner string)) {
	if cond == "true" || cond == outer {
		body(indent)
		return
	}
	e.line("%sif %s {", indent, cond)
	body(indent + "\t")
	e.line("%s}", indent)
}

func emitDispatchFn(e *emitter, fnName, kind string, specs []*Spec) {
	// Group by apiKey, picking the matching kind.
	byKey := map[int]*Spec{}
	for _, s := range specs {
		if s.Type != kind || !s.HasAPIKey {
			continue
		}
		byKey[s.APIKey] = s
	}
	keys := make([]int, 0, len(byKey))
	for k := range byKey {
		keys = append(keys, k)
	}
	sort.Ints(keys)

	e.line("// %s decodes a Kafka %s body from r (positioned after the request/response", fnName, kind)
	e.line("// header) into the appropriate generated struct, dispatched on apiKey.")
	e.line("func %s(r *Reader, apiKey, apiVersion int16) (Message, error) {", fnName)
	e.line("\tvar m Message")
	e.line("\tswitch apiKey {")
	for _, k := range keys {
		s := byKey[k]
		e.line("\tcase %d:", k)
		e.line("\t\tm = &%s{}", s.Name)
	}
	e.line("\tdefault:")
	e.line("\t\treturn nil, fmt.Errorf(\"kafkaproto: unsupported %s apiKey %%d\", apiKey)", kind)
	e.line("\t}")
	e.line("\tif err := m.Decode(r, apiVersion); err != nil {")
	e.line("\t\treturn nil, err")
	e.line("\t}")
	e.line("\treturn m, nil")
	e.line("}")
	e.line("")
}
